### ISSUE TITLE
Bashtop crashes when trying to launch

### ISSUE THREAD

**Issue by GoDzM4TT3O** [aristocratos/bashtop#1]
Hello there!
I just stumbled upon your project on Reddit!

I decided to try it out but, unfortunately, when trying to launch it, it crashes.
I have bash 5.0.3, and the terminal window is fullscreen.

When trying to launch bashtop, it just crashes/closes unexpectedly without giving out any message.

How can I fix this?

**Comment by aristocratos** [comment]
Hi.
Can you post the output from ~/.config/bashtop/error.log

**Comment by GoDzM4TT3O** [comment]
I posted a photo of what I see for half a second [on Reddit](https://www.reddit.com/user/GoDzM4TT3O/comments/fvl9vz/bashtop_crashes_upon_launch_this_is_what_i_see/)

**Comment by GoDzM4TT3O** [comment]
Here is [error.log](https://www.reddit.com/user/GoDzM4TT3O/comments/fvlcp2/bashtop_errorlog/)

**Comment by aristocratos** [comment]
Just pushed a fix.

**Comment by GoDzM4TT3O** [comment]
Thank you, I will try it out later to see if it works.

**Comment by GoDzM4TT3O** [comment]
By the way you have a spelling mistake under "Dependencies":

bash (v4.4 or later) Script functionality will most probably **brake** (should be **break** ) with earlier versions.
Bash version 5 is higly recommended to make use of $EPOCHREALTIME variable instead of alot of external date command calls.

**Comment by aristocratos** [comment]
Not a native english speaker so probably gonna be a lot of those :)

**Comment by GoDzM4TT3O** [comment]
Thanks, the bug was fixed. You can now close this issue, but please fix that spelling mistake :)
