### ISSUE TITLE
[BUG] "Draw clock" option doesn't persist after upgrading bashtop

### ISSUE THREAD

**Issue by murrayf** [aristocratos/bashtop#105]
**Describe the bug**
My custom draw clock option is: "%d/%m/%y - %X". It displays correctly but when I switch to a newer version of bashtop  only the default %X remains. Other custom options like "Custom cpu name" keep the previous configuration and works as expected...
[A clear and concise description of what the bug is.]

**To Reproduce**

[Steps to reproduce the behavior:]

**Expected behavior**
keep all custom configuration parameters after upgrading to a newer version.
[A clear and concise description of what you expected to happen.]

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - Bashtop version: 0.8.25
 - Linux distribution and version:Ubuntu 20.04 LTS x86_64
 - Terminal used: Tilix
 - Font used: don't know
 - Bash version, "bash --version" (version 4.4 or above is required): 5.0.16(1)-release
 - Locales: output of "locale -v"
LANG=es_ES.UTF-8
LANGUAGE=es_ES
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC=es_ES.UTF-8
LC_TIME=es_ES.UTF-8
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY=es_ES.UTF-8
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER=es_ES.UTF-8
LC_NAME=es_ES.UTF-8
LC_ADDRESS=es_ES.UTF-8
LC_TELEPHONE=es_ES.UTF-8
LC_MEASUREMENT=es_ES.UTF-8
LC_IDENTIFICATION=es_ES.UTF-8
LC_ALL=
**Additional context**

contents of `$HOME/.config/bashtop/error.log`
not applicable
(enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing)

Congratulations for bashtop,
Alberto.
:)

**Comment by aristocratos** [comment]
It's caused by the delimiter used for `sed` being "/".

Will add fix to correctly escape "/" if found in next update.

**Comment by murrayf** [comment]
... thanks, I close the issue then...

**Comment by aristocratos** [comment]
Fixed in v0.8.26
