### ISSUE TITLE
Recommendation for GPU monitoring from the TODO List.[REQUEST]

### ISSUE THREAD

**Issue by vspitz** [aristocratos/bashtop#108]
I hate being the good idea fairy and not having a roadmap to present for the way forward, but I just don't know enough.  That being said, have you looked into integrating the codebase for the "nvtop" application.  I run Kali 2020.1 and one of the apps i have installed form their repository is nvtop.

I'm attaching a screenshot as well for your consideration.  I get it, this is very particular, and only supports Nvidia cards but it might help you get to your end goal of a brand independent GPU monitor.

![Screenshot 2020-05-06 17:47:55](https://user-images.githubusercontent.com/30415988/81231855-df895180-8fc1-11ea-82a5-838121190928.png)

Below are the particulars:

Package: nvtop
Version: 1.0.0-1
Priority: optional
Section: contrib/utils
Maintainer: Maxime Schmitt <maxime.schmitt91@gmail.com>
Installed-Size: 76.8 kB
Depends: libc6 (>= 2.17), libncurses6 (>= 6), libncursesw6 (>= 6), libnvidia-ml1 (>= 346), libtinfo6 (>= 6)
Homepage: https://github.com/Syllo/nvtop
Download-Size: 26.6 kB
APT-Manual-Installed: yes
APT-Sources: http://http.kali.org/kali kali-rolling/contrib amd64 Packages
Description: Interactive NVIDIA GPU process monitor
 Nvtop is a ncurses-based GPU monitoring interface which provides information
 on the GPU states (GPU and memory utilization, temperature, etc) and well as
 information about the processes executing on the GPUs.

**Comment by aristocratos** [comment]
Nvtop is a C program, bashtop is a bash script. So not possible.
Look at #26 for the current thinking on how to implement GPU usage.
