### ISSUE TITLE
[REQUEST] Optional update notification 

### ISSUE THREAD

**Issue by Generator** [aristocratos/bashtop#109]
**Is your feature request related to a problem? Please describe.**
Update notification is a little annoying, some distros have is own package, until the package gets update the notification will continue to appear.

**Describe the solution you'd like**
Option to disable update notification on configuration file.

**Describe alternatives you've considered**
Replace notification with icon on bashtop (e.g. U appears on application )

**Comment by aristocratos** [comment]
Sure, is it the desktop notification that's annoying, or the menu "update available" text too?

**Comment by aristocratos** [comment]
@Generator Added in v0.8.27
