### ISSUE TITLE
[REQUEST] Show absolute total values of all disks on system...

### ISSUE THREAD

**Issue by murrayf** [aristocratos/bashtop#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'd like you implement something than display total result of all disk in the system.
In bash this can be achieve using this command:
df -h --total|grep total
You can show this info as you consider in disks section.
I find this result very useful so it would be great to show it.

**Describe alternatives you've considered**

**Additional context**
Thanks,
Alberto.

**Comment by aristocratos** [comment]
It would be possible to just add the sizes of all partitions currently displayed without another call to `df`. It would however exclude the sizes of disks not currently showing by size constraints also.

Will take a look when I've got time.
