### ISSUE TITLE
[BUG] CPU name is truncated

### ISSUE THREAD

**Issue by ggardet** [aristocratos/bashtop#114]
**Describe the bug**
CPU name is truncated. In my case, it should display `Cortex-A72` and it displays `Cortex-A7`.
On another system, it should display `Cortex-A53` and it displays `Cortex-A5`.

**To Reproduce**
Run bashtop on Arm systems

**Expected behavior**
It should show the full name

**Screenshots**
None.

**Info (please complete the following information):**
 - Bashtop version: 0.18.6
 - Linux distribution and version: openSUSE Tumbleweed
 - Terminal used: ssh connection
 - Font used: 
 - Bash version, "bash --version" (version 4.4 or above is required): 5.0.16
 - Locales: output of "locale -v":
```
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

**Additional context**

None.

**Comment by aristocratos** [comment]
> CPU name is truncated.

Text length is limited by size of the box. If it wasn't it would write over other items...

If it bothers you, you can change the name with the "Custom cpu name" option to for example "CortexA53" without the dash, and it would fit.
