### ISSUE TITLE
[BUG] Usage bars are full

### ISSUE THREAD

**Issue by vdo** [aristocratos/bashtop#120]
**Describe the bug**

All the horizontal usage bars are showing up as full with 0.8.31 version

**To Reproduce**
Just run bastop

**Screenshots**
Expected:
![Screenshot_2020-05-21_10-17-08](https://user-images.githubusercontent.com/170204/82539041-052f6280-9b4d-11ea-8ada-d13a8a9ca2f5.png)
Result:
![Screenshot_2020-05-21_10-23-27](https://user-images.githubusercontent.com/170204/82539043-06f92600-9b4d-11ea-9fd1-3ad91b1d8912.png)

 - Bashtop version: 0.8.38
 - Linux distribution and version: Linux spectre 5.6.11-1-MANJARO #1 SMP PREEMPT Wed May 6 10:20:32 UTC 2020 x86_64 GNU/Linux
 - Terminal used: Xfce4-terminal
 - Font used: terminus
 - Bash version: GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
 - Locales:
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by aristocratos** [comment]
Fixed in v0.8.32
Forgot some double quotes in the added theme error checking...
