### ISSUE TITLE
[REQUEST] Add CPU temperature for AMD

### ISSUE THREAD

**Issue by testsieger73** [aristocratos/bashtop#121]
**Is your feature request related to a problem? Please describe.**
I would like to use bashtop as my only monitoring tool. There is an option for CPU temperature in Options, but my CPU (AMD Zen 2 Ryzen 7 3700X) doesn't seem to be supported.

**Describe the solution you'd like**
`sensors` shows a set of CPU related temperature sensors (Tctl, Tdie, SMBUSMASTER), preferrably Tctl or Tdie should be available.

**Describe alternatives you've considered**
Second terminal with `sensors | grep Tdie`

**Additional context**

**Comment by aristocratos** [comment]
Support for Ryzen cpu temps is already present, if it's not working for you make a bug report with the required info from the template.

**Comment by perkinslr** [comment]
I can confirm that per ccd temperature readings are working here (3800x).  Note that lm-sensors still doesn't have per thread reporting, as AMD has not disclosed how to get that information (yet?).  One thing that is included in the lm-sensors output but not reported is the SOC and CPU Amperage.  

You do need a recent kernel to get the per ccd temperatures (5.6 or later).

**Comment by testsieger73** [comment]
Thank you, I realized that I ran an outdated version from official repos, now with git-version 0.9.0 it works.
