### ISSUE TITLE
[BUG] bashtop going crazy

### ISSUE THREAD

**Issue by sushione** [aristocratos/bashtop#123]
**Describe the bug**
When launched it run smooth for some minutes until graphs begins to be completly crazy

**To Reproduce**
Nothing to do, just let it run and watch... This issue is present since early release (0.8.x)

**Expected behavior**
clear and beautyfull terminal ASCII graphs :-)

**Screenshots**
![Screen Shot 2020-05-24 at 13 32 19](https://user-images.githubusercontent.com/38793416/82753889-af1b2300-9dc9-11ea-8f11-0feb2b6e71cc.png)

**Info (please complete the following information):**
 - Bashtop version: latest 0.9.1
 - Linux distribution and version: DietPi 6.30 (based on ARMbian) on ASUS TinkerBoard S
 - Terminal used: Putty on Win10 - iTerm2 on macOS
 - Font used: 
 - Bash version, "bash --version" (version 4.4 or above is required):
GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)
 - Locales: output of "locale -v"
LANG=
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8

**Additional context**

contents of `$HOME/.config/bashtop/error.log`
GNU nano 3.2
.config/bashtop/error.log                                                                                                             

New instance of bashtop version: 0.8.29 Pid: 2383
New instance of bashtop version: 0.8.30 Pid: 8517
New instance of bashtop version: 0.8.30 Pid: 16346
New instance of bashtop version: 0.8.31 Pid: 27961
00:19:44 ERROR: On line 1726
00:19:44 ERROR: On line 1726 (MUTED!)
New instance of bashtop version: 0.9.0 Pid: 27057
15:14:58 ERROR: On line 281
16:43:28 ERROR: On line 520
New instance of bashtop version: 0.9.0 Pid: 29636
New instance of bashtop version: 0.9.0 Pid: 21611
New instance of bashtop version: 0.9.1 Pid: 1715

**Comment by aristocratos** [comment]
try runing `LANG=en_GB.UTF-8 bashtop`

Looks like some symbols are not showing correctly, the squares with question marks in them.

So likely a UTF8 problem where the small graphs can't find the right symbol to remove and instead keeps building.

**Comment by sushione** [comment]
You mean add `LANG=en_GB.UTF-8 bashtop` to .config/bashtop/bashtop.cfg  ?
If so, bashtop won't start anymore :(

**Comment by aristocratos** [comment]
No, just run `LANG=en_GB.UTF-8 bashtop` it will temporarily set the LANG variable.

**Comment by aristocratos** [comment]
Although, you might need to add `LANG=en_GB.UTF-8` to `/etc/locale.conf` and reboot if that is what's causing the problem.

**Comment by sushione** [comment]
It's look like it's the solution !
Everything is now working fine, will add the LANG to locale.conf to test later but can't reboot right now :D
Thanks

**Comment by aristocratos** [comment]
No problem.

**Comment by sushione** [comment]
Sorry for delay. Yes, this resolve the bug, thank you !
