### ISSUE TITLE
ERROR: No UTF-8 locale found!

### ISSUE THREAD

**Issue by CaptainBloodz** [aristocratos/bashtop#125]
Worked fine until now...

env  | grep UTF is empty

env  | grep utf returns
LANG=fr_FR.utf8

What's missing?
Thks 4 ur attention, interest & support.

**Comment by aristocratos** [comment]
Use the bug report template when posting bugs, missing needed information.

**Comment by CaptainBloodz** [comment]
emerge --info bashtop
 * Failed to change nice value to '-10'
 * [Errno 1] Operation not permitted

Portage 2.3.99 (python 3.7.7-final-0, default/linux/amd64/17.1, gcc-9.3.0, glibc-2.30-r8, 5.6.14-gentoo-classic x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.6.14-gentoo-classic-x86_64-Intel-R-_Core-TM-_i3-6100_CPU_@_3.70GHz-with-gentoo-2.6
KiB Mem:     3939304 total,    507500 free
KiB Swap:    8048528 total,   7700692 free
Timestamp of repository audio-overlay: Mon, 25 May 2020 21:50:44 +0000
Head commit of repository audio-overlay: deba6463af1bdc2e5a97c60a43b7717dafe5cd3f

Timestamp of repository calculate: Tue, 26 May 2020 08:35:07 +0000
Head commit of repository calculate: cf0f174e5e5eb93227cea3f1acc3ae6143375d17

Timestamp of repository go-overlay: Mon, 25 May 2020 21:50:18 +0000
Head commit of repository go-overlay: 421d7db481d5d55fe3a7567c1ea5b6befc51897d

Timestamp of repository jellybean: Mon, 25 May 2020 21:50:57 +0000
Head commit of repository jellybean: eab0c350ca901b2396e1f5ed5ae9b0270141f1ae

Timestamp of repository linxon: Mon, 25 May 2020 21:50:44 +0000
Head commit of repository linxon: f9c1447c93729cbb33d34cee4800ffa2dea9fac4

Timestamp of repository pentoo: Tue, 26 May 2020 15:10:42 +0000
Head commit of repository pentoo: b12a75a42d705e7be419209b9b813254f95e4220

Timestamp of repository raiagent: Mon, 25 May 2020 21:50:00 +0000
Head commit of repository raiagent: 19846dbd641f393958c15bc716a05b21e371ee41

Timestamp of repository rukruk: Mon, 25 May 2020 21:50:30 +0000
Head commit of repository rukruk: c154b6d6f8cdf5fee31dc5a4929d1d03f50aa051

Timestamp of repository seden: Mon, 25 May 2020 21:50:05 +0000
Head commit of repository seden: 20525cfe3a848b5ae6ca2cc78578644fef172d28

Head commit of repository smoverlay: b69783cc4cd6b2d40771468892e9d3315ed16466

Timestamp of repository waebbl: Mon, 25 May 2020 21:50:46 +0000
Head commit of repository waebbl: 2a5c24d4ea06f50a80938795d6e0b417476595a7

Timestamp of repository gentoo: Tue, 26 May 2020 17:45:01 +0000
Head commit of repository gentoo: 7e09d0b056398b76f9c7b01d1da9770229089aa9
sh bash 5.0_p17
ld GNU ld (Gentoo 2.33.1 p2) 2.33.1
distcc 3.3.3 x86_64-pc-linux-gnu [disabled]
app-shells/bash:          5.0_p17::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.1::gentoo
dev-lang/python:          2.7.18::gentoo, 3.6.10-r2::gentoo, 3.7.7-r2::gentoo, 3.8.2-r2::gentoo
dev-util/cmake:           3.16.5::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.16.1-r1::gentoo
sys-devel/binutils:       2.33.1-r1::gentoo
sys-devel/gcc:            9.3.0::gentoo, 10.1.0::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.4-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.30-r8::gentoo
Repositories:

audio-overlay
    location: /var/db/repos/audio-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/audio-overlay.git
    masters: gentoo
    priority: -10001

calculate
    location: /var/db/repos/calculate
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/calculate.git
    masters: gentoo
    priority: -10001

das-labor
    location: /var/lib/layman/das-labor
    masters: gentoo
    priority: -10001

go-overlay
    location: /var/db/repos/go-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/go-overlay.git
    masters: gentoo
    priority: -10001

jellybean
    location: /var/db/repos/jellybean
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/jellybean.git
    masters: gentoo
    priority: -10001

linxon
    location: /var/db/repos/linxon
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/linxon.git
    masters: gentoo
    priority: -10001

pentoo
    location: /var/db/repos/pentoo
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/pentoo.git
    masters: gentoo
    priority: -10001

raiagent
    location: /var/db/repos/raiagent
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/raiagent.git
    masters: gentoo
    priority: -10001

rukruk
    location: /var/db/repos/rukruk
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/rukruk.git
    masters: gentoo
    priority: -10001

seden
    location: /var/db/repos/seden
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/seden.git
    masters: gentoo
    priority: -10001

smoverlay
    location: /var/db/repos/smoverlay
    sync-type: git
    sync-uri: https://git.s-morozov.net/gentoo-overlays/smoverlay.git
    masters: gentoo
    priority: -10001

waebbl
    location: /var/db/repos/waebbl
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/waebbl.git
    masters: gentoo raiagent
    priority: -10001

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.europe.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts: 
    sync-rsync-verify-metamanifest: no
    sync-rsync-verify-jobs: 1

gnu-elpa
    location: /var/lib/layman/gnu-elpa
    masters: gentoo
    priority: 50

lisp
    location: /var/lib/layman/lisp
    masters: gentoo
    priority: 50

melpa
    location: /var/lib/layman/melpa
    masters: gnu-elpa gentoo
    priority: 50

local-repo
    location: /var/db/repos/local-repo
    masters: gentoo
    priority: 10000

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -mtune=skylake  -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.4/ext-active/ /etc/php/cgi-php7.4/ext-active/ /etc/php/cli-php7.4/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/splash /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=skylake -mtune=skylake  -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize    "
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--alert y 			--alphabetical 			--ask-enter-invalid 			--autounmask y  			--autounmask-only n  			--autounmask-unrestricted-atoms y  	--autounmask-write y 			--misspell-suggestions n 		--noconfmem 			--nospinner   			--tree 		--with-bdeps y"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=skylake -mtune=skylake  -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms split-elog strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-march=skylake -mtune=skylake  -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize"
GENTOO_MIRRORS="http://ftp.free.fr/mirrors/ftp.gentoo.org/ https://mirrors.evowise.com/gentoo/ http://mirror.dkm.cz/gentoo/ http://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ http://mirror.netcologne.de/gentoo/ http://mirror.leaseweb.com/gentoo/ http://mirror.bytemark.co.uk/gentoo/ http://gentoo.mirror.web4u.cz/ http://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/"
LANG="fr_FR.utf8"
LDFLAGS="  -Wl,-O1       -Wl,-fuse-ld=bfd  -Wl,--enable-new-dtags  -Wl,-z,relro -Wl,-z,now -fno-plt -march=skylake -mtune=skylake  -O2             -pipe -ftree-loop-vectorize -ftree-slp-vectorize "
LINGUAS="fr"
MAKEOPTS="-j3 -l3"
PKGDIR="/var/cache/binpkgs"
PORTAGE_COMPRESS="lzma"
PORTAGE_COMPRESS_FLAGS="-9"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="amd64 asm minimal split-usr" ABI_X86="64" ALSA_CARDS="hda-intel" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GRUB_PLATFORMS="pc" INPUT_DEVICES="libinput" KERNEL="linux" L10N="fr" PHP_TARGETS="php7-4" PYTHON_SINGLE_TARGET="python3_7" PYTHON_TARGETS="python2_7 python3_6 python3_7" QEMU_USER_TARGETS="aarch64" RUBY_TARGETS="ruby25" USERLAND="GNU" VIDEO_CARDS="intel i965"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_RSYNC_EXTRA_OPTS

=================================================================
                        Package Settings
=================================================================

sys-process/bashtop-9999::local-repo was built with the following:
USE="" ABI_X86="(64)"

**Comment by aristocratos** [comment]
> >**Info (please complete the following information):**
>  - Bashtop version:
>  - (Linux) Linux distribution and version:
>  - (Linux) Data collection type (/proc or psutil):
>  - (OSX/FreeBSD) Os release version:
>  - Terminal used:
>  - Font used:
>  - Bash version, "bash --version" (version 4.4 or above is required):
>  - Locales: output of "locale -v"

**Comment by CaptainBloodz** [comment]
Bashtop version: 0.9.5
Terminal used: console
bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
locale -v
LANG=fr_FR.utf8
LC_CTYPE="fr_FR.utf8"
LC_NUMERIC="fr_FR.utf8"
LC_TIME="fr_FR.utf8"
LC_COLLATE="fr_FR.utf8"
LC_MONETARY="fr_FR.utf8"
LC_MESSAGES="fr_FR.utf8"
LC_PAPER="fr_FR.utf8"
LC_NAME="fr_FR.utf8"
LC_ADDRESS="fr_FR.utf8"
LC_TELEPHONE="fr_FR.utf8"
LC_MEASUREMENT="fr_FR.utf8"
LC_IDENTIFICATION="fr_FR.utf8"
LC_ALL=


cat $HOME/.config/bashtop/error.log
 
New instance of bashtop version: 0.8.27 Pid: 4325
 
New instance of bashtop version: 0.9.4 Pid: 26820
 
New instance of bashtop version: 0.9.4 Pid: 28099
 
New instance of bashtop version: 0.9.4 Pid: 28545
 
New instance of bashtop version: 0.9.4 Pid: 29937
 
New instance of bashtop version: 0.9.4 Pid: 23500

**Comment by aristocratos** [comment]
Also

> contents of `$HOME/.config/bashtop/error.log`

**Comment by aristocratos** [comment]
Can you post the output of `locale -a` and `shopt` also.

**Comment by CaptainBloodz** [comment]
locale -a
C
C.utf8
fr_FR.utf8
POSIX
----------------------------------------------------------------------------------------------
shopt
autocd         	off
assoc_expand_once	off
cdable_vars    	off
cdspell        	off
checkhash      	off
checkjobs      	off
checkwinsize   	on
cmdhist        	on
compat31       	off
compat32       	off
compat40       	off
compat41       	off
compat42       	off
compat43       	off
compat44       	off
complete_fullquote	on
direxpand      	off
dirspell       	off
dotglob        	off
execfail       	off
expand_aliases 	on
extdebug       	off
extglob        	on
extquote       	on
failglob       	off
force_fignore  	on
globasciiranges	on
globstar       	off
gnu_errfmt     	off
histappend     	on
histreedit     	off
histverify     	off
hostcomplete   	off
huponexit      	off
inherit_errexit	off
interactive_comments	on
lastpipe       	off
lithist        	off
localvar_inherit	off
localvar_unset 	off
login_shell    	on
mailwarn       	off
no_empty_cmd_completion	on
nocaseglob     	off
nocasematch    	off
nullglob       	off
progcomp       	on
progcomp_alias 	off
promptvars     	on
restricted_shell	off
shift_verbose  	off
sourcepath     	on
xpg_echo       	off

**Comment by CaptainBloodz** [comment]
cat /etc/locale.gen
# /etc/locale.gen: list all of the locales you want to have on your system.
# See the locale.gen(5) man page for more details.
#
# The format of each line:
# <locale name> <charset>
#
# Where <locale name> starts with a name as found in /usr/share/i18n/locales/.
# It must be unique in the file as it is used as the key to locale variables.
# For non-default encodings, the <charset> is typically appended.
#
# Where <charset> is a charset located in /usr/share/i18n/charmaps/ (sans any
# suffix like ".gz").
#
# All blank lines and lines starting with # are ignored.
#
# For the default list of supported combinations, see the file:
# /usr/share/i18n/SUPPORTED
#
# Whenever glibc is emerged, the locales listed here will be automatically
# rebuilt for you.  After updating this file, you can simply run `locale-gen`
# yourself instead of re-emerging glibc.

#en_US ISO-8859-1
#en_US.UTF-8 UTF-8
#ja_JP.EUC-JP EUC-JP
#ja_JP.UTF-8 UTF-8
#ja_JP EUC-JP
#en_HK ISO-8859-1
#en_PH ISO-8859-1
#de_DE ISO-8859-1
#de_DE@euro ISO-8859-15
#es_MX ISO-8859-1
#fa_IR UTF-8
#fr_FR ISO-8859-1
#fr_FR@euro ISO-8859-15
#it_IT ISO-8859-1
fr_FR.UTF-8 UTF-8

**Comment by aristocratos** [comment]
Test v0.9.6
Should be fixed.

**Comment by CaptainBloodz** [comment]
Thks, now testing...
