### ISSUE TITLE
When exiting, console prompt starts beyond column 120 here.

### ISSUE THREAD

**Issue by CaptainBloodz** [aristocratos/bashtop#126]
Doesn't occurs in terminal, only in console.
Not blocking of course, just a little disgraceful.
Plz consider as a minor issue.

Thks 4 ur attention, interest & support.

**Comment by aristocratos** [comment]
Not a bug. Bashtop is not designed to be run in a console.

Under compatibility:
>   For correct display, a terminal with support for:
> 
>     24-bit truecolor
>     Wide characters
>
