### ISSUE TITLE
Make Bashtop installable on Solus OS

### ISSUE THREAD

**Issue by theunclemez** [aristocratos/bashtop#129]
I Git cloned Bashtop to install it Solus OS but install never worked.
I checked on all dependencies and they where there but for some reasons nothing was happening.
push the sudo make install command and it just go back to the prompt
type bashtop and nothing but command unknown

Possible to get it sorted? so Solus users can install it in manual mode since bashtop is not on Solus OS repos yet.

**Comment by aristocratos** [comment]
That's because Solus by default don't have ´/usr/local/bin´ in path, you either have to add it to path or manually copy ´bashtop´ to a directory that is in path.

I won't change the makefile because a small minority of distributions don't follow the norm.
