### ISSUE TITLE
[BUG] Issue on latest Proxmox + Fedora 30

### ISSUE THREAD

**Issue by seitzbg** [aristocratos/bashtop#13]
**Describe the bug**
Seems to have an issue with lots of mounts / maybe ZFS?

**To Reproduce**
Run bashtop

**Expected behavior**
Prettyness

**Screenshots**
App exits after drawing the boxes with: 
./bashtop: line 1171: -: syntax error: operand expected (error token is "-")

**Info (please complete the following information):**
 - Debian GNU/Linux 10 (buster
 - System locale: en_US.UTF-8
 - Bash version: GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

**Additional context**
New instance of bashtop version: 0.8.3 Pid: 33115
./bashtop: line 1171: -: syntax error: operand expected (error token is "-")

New instance of bashtop version: 0.8.3 Pid: 33612
./bashtop: line 1171: -: syntax error: operand expected (error token is "-")

New instance of bashtop version: 0.8.3 Pid: 36473
./bashtop: line 1171: -: syntax error: operand expected (error token is "-")

New instance of bashtop version: 0.8.3 Pid: 37120
git/bashtop/bashtop: line 1171: -: syntax error: operand expected (error token is "-")

New instance of bashtop version: 0.8.3 Pid: 37775
git/bashtop/bashtop: line 1171: -: syntax error: operand expected (error token is "-")

**Comment by aristocratos** [comment]
Seems like error.log doesn't tell much beyond it crashing when creating graphs.
Would you mind running `bashtop --debug` and posting the resulting "$HOME/.config/bashtop/tracing.log"?

**Comment by aristocratos** [comment]
Fixed in v0.8.4 [1c40f2e](https://github.com/aristocratos/bashtop/commit/1c40f2e77029ea97f94b1af92b585e54c7add495)

**Comment by seitzbg** [comment]
Better but now I see:

![image](https://user-images.githubusercontent.com/171158/80154556-caf29580-858d-11ea-8f52-a6850f703db5.png)
