### ISSUE TITLE
[REQUEST]How to install bashtop on centos7?

### ISSUE THREAD

**Issue by himrlawrrence** [aristocratos/bashtop#135]
[root@ bashtop]# dnf config-manager --set-enabled PowerTools
Error: No matching repo to modify: PowerTools.
[root@ bashtop]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core

==>it seems bashtop cannot install on centos 7?

**Comment by aristocratos** [comment]
CentOS 7 has an outdated version of bash. You will have to manually install bashtop and upgrade bash to get it working. Will update readme to make clear that the instructions are for CentOS 8 or later.
