### ISSUE TITLE
[REQUEST] Option to keep original terminal title?

### ISSUE THREAD

**Issue by theytaz** [aristocratos/bashtop#136]
When bashtop is running, the terminal title is changed to 'BashTOP'
Could you please make this optional?

Not easy when you have have a lot of windows/hosts...

As a quick workaround, I suggest replacing:
echo -en "\033]0;BashTOP\a"
by:
echo -en "\033]0;${TERMINAL_TITLE} BashTOP\a"

**Comment by aristocratos** [comment]
Will change to include your suggested `${TERMINAL_TITLE}` in next update.

**Comment by aristocratos** [comment]
@theytaz 
Added in v0.9.10
