### ISSUE TITLE
Problem with theme[main_fg] for process box

### ISSUE THREAD

**Issue by Abu-Raziel** [aristocratos/bashtop#138]
**Describe the bug**

The process box generates different color for main_fg text.
If making a custom theme. main_fg changes uniformly across the application,
except for the process box. It looks like the blue and green values are getting mixed up
for main_fg.

**To Reproduce**

when **theme[main_fg] = #00ff00**  (pure green), the text in process box becomes black
when **theme[main_fg] = #0000ff**  (pure blue), the text in process box looks like #00ffff
when **theme[main_fg] = #ff0000**  (pure red), the text in process box looks correct
when **theme[main_fg] = #ffffff**      (white), the text in process box looks correct
when **theme[main_fg] = #00ffff**    (cyan), the text in process box looks correct

**Expected behavior**

Expected main_fg text to change to the same color even in the process box.

**Screenshots**

PFA
[bashtop bug.zip](https://github.com/aristocratos/bashtop/files/4773837/bashtop.bug.zip)

.

**Info (please complete the following information):**
 - Bashtop version: 0.9.9+git222-b4a3e81~ubuntu20.04.1
 - (Linux) Linux distribution and version: Ubuntu 20.04
 - (Linux) Data collection type (/proc or psutil): /proc
 - (OSX/FreeBSD) Os release version:
 - Terminal used: guake
 - Font used: ubuntu mono nerd regular (patched nerd fonts)
 - Bash version, "bash --version" (version 4.4 or above is required): 5.0.16
 - Locales: output of "locale -v"

**Additional context**

contents of `$HOME/.config/bashtop/error.log`

(enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing)

**Comment by aristocratos** [comment]
Took a closer look at the draw_processes function and noticed I was setting text color to RBB instead of RGB.
Will be fixed in next update. Will also make the processes gradient look a lot better in most themes.

**Comment by Abu-Raziel** [comment]
Awesome! shall look forward to it.

**Comment by Abu-Raziel** [comment]
![Screenshot from 2020-06-15 18-07-34](https://user-images.githubusercontent.com/13904068/84658760-02e5db80-af34-11ea-931b-288497857873.png)

Issue is fixed post upgrade !!! :)
