### ISSUE TITLE
[BUG] Arch Linux Guake Terminal BASHTOP crash

### ISSUE THREAD

**Issue by MrDoAsILike** [aristocratos/bashtop#142]
Describe the bug

Hangs at the command line after entering "bashtop" on Guake Terminal v3.7.0-1& Konsole v20.0.4.2-1 & Termite 15-1 & Terminator v1.92-2 & Yakuake v20.04.2-1 on ArcoLinuxD v20.6 with Cinnamon DE.

To Reproduce

Run Guake Terminal after in Guake run Bashtop

Expected behavior

Not crash's

Screenshots

Not applicable

Info (please complete the following information):

Arch source :
https://github.com/aristocratos/bashtop

bashtop version:
bashtop v0.9.12-1

(Linux) Linux distribution and version: 
ArcolinuxD 20.6 

Terminal used: Guake terminal v3.7.0-1 & Konsole v20.0.4.2-1 & Termite 15-1 & Terminator v1.92-2 & Yakuake v20.04.2-1

Font:
Sans 9 [GTK2/3]

Bash version, "bash --version" (version 4.4 or above is required): GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

Locales: output of "locale -v" :

LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.utf8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.utf8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

Additional context

contents of $HOME/.config/bashtop/error.log :

/usr/bin/bashtop: line 1374: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1384: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1390: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1374: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1384: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1390: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1374: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1384: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1390: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1374: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1384: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")

**Comment by aristocratos** [comment]
I've added some extended error checking in v0.9.13
Try updating hopefully we will get some useful output in the error.log if the problem persists.

**Comment by MrDoAsILike** [comment]
Still no luck. I uninstalled it via package manager (as that's how i originally had it installed) and redownloaded it via git clone after looking over the other post with the same issue. So after doing that and then checking my /usr/local/bin for the bashtop executable in emacs, I saw the version declare line (94 I believe) stating that it was v0.9.13 as well as the $HOME/.config/bashtop/bashtop.cfg file.The same symptoms persist. 

Here's my error.log snippet:

/usr/bin/bashtop: line 1374: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1384: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")
/usr/bin/bashtop: line 1390: ((: Pid: Program:       Tr: User:    Mem%       Cpu%: syntax error in expression (error token is ": Program:       Tr: User:    Mem%       Cpu%")

It's repetitive after this point

**Comment by aristocratos** [comment]
@MrDoAsILike 
Possible fix and additional error checking added in v0.9.14

**Comment by MrDoAsILike** [comment]
Fixed after v0.9.14 update. Thank You.

**Comment by aristocratos** [comment]
@MrDoAsILike 
Would you mind posting your `error.log` again with the latest version, need to see if the extended error checking provided any more info on what was going wrong.

**Comment by MrDoAsILike** [comment]
Sure. I'm away from my laptop right now. Give me about 15mins and I got you.

**Comment by MrDoAsILike** [comment]
This is all that was in the log with an instance of bashtop running:

New instance of bashtop version: 0.9.14 Pid: 76374

**Comment by aristocratos** [comment]
Ok, thanks. Just wanted to make sure it wasn't a issue with psutil, would have shown up in the log in that case.

**Comment by MrDoAsILike** [comment]
Glad to have helped. Keep rockin out. Bashtop is my preferred top now. Thanks for your work.
