### ISSUE TITLE
[BUG] BashTop very slow on WSL

### ISSUE THREAD

**Issue by Kl0ven** [aristocratos/bashtop#143]
**Describe the bug**

Hi, I updated Bashtop to version v0.9.13 from an old version (can't remeber wich one). 
All the interface is very slow to update and respond to input, from 2 to 15 second to update.
Even with time step set to 100ms
Is WSL even supported ? I'm not sure. 

**To Reproduce**

```
$ git clone https://github.com/aristocratos/bashtop.git 
$ ./bashtop
```
On WSL1 - ubuntu 18.04

**Expected behavior**

update every time_step and respond to input (look like issue #36, but way more slow, and display is slow too)

**Info (please complete the following information):**
 - Bashtop version: v0.9.13
 - (Linux) Linux distribution and version: Ubuntu 18.04 on WSL1 on Windows 10 v1909 Family
 - (Linux) Data collection type (/proc or psutil): proc
 - Terminal used: windows terminal
 - Font used: MesloLGS NF
 - Bash version, "bash --version" (version 4.4 or above is required): zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Locales: output of "locale -v"
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Additional context**

contents of `$HOME/.config/bashtop/error.log`
```
$ cat error.log                                                         
New instance of bashtop version: 0.8.4 Pid: 1157
02:25:03 PM ERROR: On line 1412
02:25:27 PM ERROR: On line 1412 (MUTED!)

New instance of bashtop version: 0.8.4 Pid: 109
10:56:03 AM ERROR: On line 1412
10:56:26 AM ERROR: On line 1412 (MUTED!)

New instance of bashtop version: 0.9.12 Pid: 1573

New instance of bashtop version: 0.9.12 Pid: 3485

New instance of bashtop version: 0.9.13 Pid: 3747

New instance of bashtop version: 0.9.13 Pid: 3952

New instance of bashtop version: 0.9.13 Pid: 48

New instance of bashtop version: 0.9.13 Pid: 907

# rm -rf bashtop/
# git clone https://github.com/aristocratos/bashtop.git


03:35:23 PM ERROR: On line 633

New instance of bashtop version: 0.9.13 Pid: 2018

New instance of bashtop version: 0.9.13 Pid: 2094
```

**Comment by aristocratos** [comment]
@Kl0ven 
See issue #110 
It's a problem with wsl

> Seems to be wsl not respecting the timeout set with stty.
