### ISSUE TITLE
[BUG]net module not displaying like cpu module?

### ISSUE THREAD

**Issue by MrDoAsILike** [aristocratos/bashtop#146]
Describe the bug

Net module not displaying graph like cpu module does. (if this is not a thing and working as intended then nvm.)

To Reproduce

Run Yakuake Terminal after in Yakuake run Bashtop

Expected behavior

graph being shown like cpu module

Screenshots

https://drive.google.com/drive/folders/1stpJuGAmZK4nlZdeNUrcRVtbL487fWBY?usp=sharing

Info (please complete the following information):

Arch source :
https://github.com/aristocratos/bashtop

bashtop version:
bashtop v0.9.14

(Linux) Linux distribution and version:
ArcolinuxD 20.6

Terminal used: Yakuake terminal v3.7.0-1 & Konsole v20.0.4.2-1 & Termite 15-1 & Terminator v1.92-2 & Guake v20.04.2-1

Font:
Sans 9 [GTK2/3]

Bash version, "bash --version" (version 4.4 or above is required): GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

Locales: output of "locale -v" :

LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.utf8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.utf8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

Additional context

contents of $HOME/.config/bashtop/error.log :
(with instance running)

New instance of bashtop version: 0.9.14 Pid: 76374
 
New instance of bashtop version: 0.9.14 Pid: 181844

**Comment by aristocratos** [comment]
A screenshot would be helpful.

**Comment by MrDoAsILike** [comment]
Appended shareable GDrive link. 4 pictures using different themes. If you need more just give me a holler.

**Comment by aristocratos** [comment]
Well, I can see plots on the graph on two of the screenshots. The graph scales down to show ranges between 10-1 kilobytes at it's lowest, if your network activity is below 1000 bytes you're likely not going to see any plots on the graph. This is to reduce rescaling of the network graphs (which costs cpu) when there is essentially no network activity.

So not a bug, but working as intended.

**Comment by MrDoAsILike** [comment]
Awesome. Thanks for your timely response to all this. I'll close the report.
