### ISSUE TITLE
[BUG] psutil fails to detect disk

### ISSUE THREAD

**Issue by remisalmon** [aristocratos/bashtop#148]
**Describe the bug**

`disks` is empty since bashtop 0.9.12 when using psutil (no issue with 0.9.11 or when psutil is disabled).

error.log:
```
PSUTIL ERROR! Command: get_disks(exclude='squashfs')
not sure how to interpret line ' 259       0 nvme0n1 141120 36879 7416840 28472 90526 90168 7147797 220546 0 51517 201021 25599 0 331591080 4194 4517 13968\n'
```

**Screenshots**

![image](https://user-images.githubusercontent.com/26257211/85309995-ae30ec00-b470-11ea-9caa-2d6377822deb.png)

**Info**
 - Bashtop version: 0.9.14
 - (Linux) Linux distribution and version: Fedora 32
 - (Linux) Data collection type (/proc or psutil): psutil
 - Terminal used: xfce4-terminal
 - Font used: Deja Vu Sans Mono
 - Bash version, "bash --version" (version 4.4 or above is required): 5.0.17
 - Locales: LANG=en_US.utf8

**Comment by aristocratos** [comment]
https://github.com/giampaolo/psutil/issues/1692
Seems to be a psutil issue, I can add a fallback to using `df` if psutil fails on disks collection.
You will need [iostat from sysstat](https://github.com/sysstat/sysstat) however if you want disk io without psutil.

**Comment by aristocratos** [comment]
@remisalmon @zoof
Fixed in v0.9.15

**Comment by zoof** [comment]
Still not working for me:

```
New instance of bashtop version: 0.9.15 Pid: 6097
PSUTIL ERROR! Command: get_disks(exclude='squashfs')
not sure how to interpret line '   8       0 sda 25996 12636 2038963 954372 2870 5367 306602 57953 0 79944 971440 0 0 0 0 592 36629\n'
```

**Comment by aristocratos** [comment]
An error on my part in the last update, will be fixed shortly.

**Comment by aristocratos** [comment]
Should be fixed in v0.9.16

**Comment by remisalmon** [comment]
Worked for me. Feel free to reopen until upstream issue is closed.

**Comment by aristocratos** [comment]
This issue is fixed in psutil 5.7.0, so if you update psutil bashtop won't fallback to df.

**Comment by teedohs** [comment]
Yea, this still seems to be an issue. I'm also running the latest version `0.9.25` but no disks are displayed even after verifying the proper mount point names in the `menu` section. In `bpytop`, the disks show up fine even with the proper/same names

**Comment by KesleyDavid** [comment]
same problem for me

**Comment by x4D48** [comment]
same here: 
ubuntu 20.04.4 LTS, bashtop 0.9.25, python-psutil 5.5.1-1ubuntu4

**Comment by msapunov** [comment]
> I have bashtop version 0.9.25, psutil at version 5.8.0 installed, iostat installed, sysstat enabled and running as a service, i'm running bashtop as sudo and still nothing showing up on my disks. I don't know what else to do.
> 
> I should say that I've installed the snap version of bashtop.

For those who have installed snap version of bashtop - don't forget to give proper permissions via app store or "snap connect" command
