### ISSUE TITLE
[BUG] Not showing disk information

### ISSUE THREAD

**Issue by zoof** [aristocratos/bashtop#149]
**Describe the bug**

Following some recent change in `bashtop`, disk information stopped being displayed.

**To Reproduce**

run `bashtop`.

**Expected behavior**

Shows disk information

**Screenshots**

![Screenshot_2020-06-22_13-19-01](https://user-images.githubusercontent.com/1737483/85316712-31f7d200-b48b-11ea-93cd-29770544124a.png)

**Info (please complete the following information):**
 - Bashtop version: 0.9.14
 - (Linux) Linux distribution and version: Debian Buster
 - (Linux) Data collection type (/proc or psutil): /proc
 - (OSX/FreeBSD) Os release version: NA
 - Terminal used: lxterminal
 - Font used: Monospace Regular 10
 - Bash version, "bash --version" (version 4.4 or above is required): 5.0.3(1)-release
 - Locales: output of "locale -v"

```
$ locale -v
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Additional context**

contents of `$HOME/.config/bashtop/error.log`

```
New instance of bashtop version: 0.9.14 Pid: 12083
PSUTIL ERROR! Command: get_disks(exclude='squashfs')
not sure how to interpret line '   8       0 sda 84566 58472 4926850 744328 98232 98254 4651466 781960 0 296320 1344272 0 0 0 0 27181 430467\n'
```

**Comment by aristocratos** [comment]
Same as #148
