### ISSUE TITLE
[BUG] Does not use XDG Base Directory spec

### ISSUE THREAD

**Issue by Neui** [aristocratos/bashtop#15]
**Describe the bug**
It creates an config file at `$HOME/.config/bashtop/bashtop.cfg`

**To Reproduce**
1. Start `bashtop`

**Expected behavior**
Create an config file at `${XDG_CONFIG_HOME:-$HOME/.config}/bashtop/bashtop.cfg`

**Screenshots**
(none)

**Info (please complete the following information):**
 - Linux distribution and version: none, just looked at the code
 - System locale (output of "echo $LANG"): none, just looked at the code
 - Bash version: none, just looked at the code

**Additional context**
https://github.com/aristocratos/bashtop/blob/dac039e59516b4f7e8b0007413321203de447036/bashtop#L3412

There is also `$XDG_CONFIG_DIRS` you could use if you implement "config layering" (like get the (default) values from the system configuration first etc.)

See the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), and the [XDG Base Directory article on the archlinux wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory).

**Comment by aristocratos** [comment]
Good idea!
Will be added in next update.

**Comment by aristocratos** [comment]
Added in v0.8.4 [1c40f2e](https://github.com/aristocratos/bashtop/commit/1c40f2e77029ea97f94b1af92b585e54c7add495)
