### ISSUE TITLE
[BUG] Bashtop gets stuck at the initialization

### ISSUE THREAD

**Issue by fliker09** [aristocratos/bashtop#154]
Running it in Yakuake / Konsole and I get this:
![Screenshot_20200627_180814](https://user-images.githubusercontent.com/18057950/85925542-b094ab00-b8a1-11ea-98aa-caf2dbc7cb0a.png)
In error.log I see:
New instance of bashtop version: 0.9.16 Pid: 15757
I press Ctrl+C and get this in error.log:
18:09:12 ERROR: On line 2309 
/usr/bin/bashtop: line 308: echo: write error: Broken pipe
18:09:12 ERROR: On line 2816 
/usr/bin/bashtop: line 308: echo: write error: Broken pipe
18:09:13 ERROR: On line 2411 
/usr/bin/bashtop: line 308: echo: write error: Broken pipe
18:09:13 ERROR: On line 502 
/usr/bin/bashtop: line 308: echo: write error: Broken pipe
18:09:13 ERROR: On line 2411 (MUTED!)
/usr/bin/bashtop: line 2465: ( ( 538827-538814 ) * 1000 * 1000 ) / ( cpu[hz]*time_elapsed*8 ) : division by 0 (error token is "( cpu[hz]*time_elapsed*8 ) ")
/usr/bin/bashtop: line 308: echo: write error: Broken pipe
18:09:13 ERROR: On line 4671 
/usr/bin/bashtop: line 308: echo: write error: Broken pipe
18:09:14 ERROR: On line 2411 (MUTED!)
/usr/bin/bashtop: line 2465: ( ( 538838-538814 ) * 1000 * 1000 ) / ( cpu[hz]*time_elapsed*8 ) : division by 0 (error token is "( cpu[hz]*time_elapsed*8 ) ")
Meanwhile Bashtop tries to finish the initialization, tries to draw elements and quickly close afterwards.

**Info (please complete the following information):**
 - Bashtop version: 0.9.16+git240-a12ea54~ubuntu18.04.1
 - (Linux) Linux distribution and version: KDE neon 5.19.2
 - (Linux) Data collection type (/proc or psutil): tried both, same result
 - Terminal used: yakuake / konsole
 - Font used: Hack 9pt
 - Bash version, "bash --version" (version 4.4 or above is required): 4.4.20(1)-release
 - Locales: output of "locale -v"
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=C
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=C
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by aristocratos** [comment]
The timestamp function fails on your system for some reason.
Will be a fix in v0.9.19

**Comment by fliker09** [comment]
Cool! How soon it will be released? The interesting thing - at some point Bashtop was working, but I don't remember which version was that one :-|
Maybe my CPU is too old, not sure it plays a role:
$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               23
Model name:          Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
Stepping:            10
CPU MHz:             3000.005
CPU max MHz:         900.0000
CPU min MHz:         600.0000
BogoMIPS:            6000.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority dtherm

**Comment by aristocratos** [comment]
It will be released in a day or two.
If you want a fix before then you can delete line 289-312 and 318 in the script and it should work for you.

**Comment by fliker09** [comment]
Cool, thanks!

**Comment by fliker09** [comment]
New issue:
New instance of bashtop version: 0.9.19 Pid: 26623
21:43:41 ERROR: On line 2268 
I am using 0.9.19+git250-91fbc4f~ubuntu18.04.1 version

**Comment by aristocratos** [comment]
It's stopping on the command `iostat -dkz`, try running it and see what output you get. Most likely it's too outdated. Will likely run fine if you got `python3` and `psutil` installed and change `use_psutil` to `true` in you config file.

**Comment by fliker09** [comment]
New error on changing to true:

> New instance of bashtop version: 0.9.19 Pid: 5178
> PSUTIL ERROR! Command: get_disks(exclude='squashfs')
> not sure how to interpret line '   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n'
> 14:45:53 ERROR: On line 2268 
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> 14:45:53 ERROR: On line 4804 
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> 14:45:54 ERROR: On line 4804 (MUTED!)
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4804: ${pycoproc[1]}: ambiguous redirect
> /usr/bin/bashtop: line 4807: read: -t: invalid file descriptor specification
> /usr/bin/bashtop: line 4793: ${pycoproc[1]}: ambiguous redirect

As for iostat -dkz:

> $ iostat -dkz
> Linux 5.4.0-38-generic (X7DCA-L)        07/10/20        _x86_64_        (8 CPU)
> 
> Device             tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
> sda               0.09         2.94         0.00      15001          0
> sdb               0.02         0.44         0.00       2220          0
> sdc               3.41        80.87      1057.40     412429    5392342
> sdd               3.19       108.19      1028.33     551729    5244110
> sde              17.14       398.34       233.42    2031373    1190340
> sdf               3.18       111.19      1022.69     567053    5215366
> sdg               3.23       126.78      1006.64     646538    5133490
> md0               4.66       331.25      3021.54    1689229   15408736
> sdk              47.21      3018.26         0.04   15392032        184

**Comment by aristocratos** [comment]
Which psutil version are you using? `python3 -c "import psutil; print(psutil.version_info)"`
If it's less than 5.7.0, run `sudo pip3 install --upgrade psutil` and try again.

**Comment by fliker09** [comment]
It was 5.4.2. Upgraded and got 5.7.0 - now it works, thanks!

**Comment by aristocratos** [comment]
No problem, gonna add the psutil version requirement to the readme.
