### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by jjoeshua** [aristocratos/bashtop#156]
I try to update to new version, after cloning I have the same old version.
I am using Ubuntu Focal Fossa.
I also try reinstalling it but always get the same version that I have, I can update it..
what am I doing wrong.. 
how to update it properly?

**Comment by aristocratos** [comment]
Would help if you posted what commands and in what order you are running them to update. It's kinda hard to say what's going wrong without having any data on what you are doing.

**Comment by jjoeshua** [comment]
git clone https://github.com/aristocratos/bashtop.git
fatal: destination path 'bashtop' already exists and is not an empty directory.
dzoiejowiee@dzoiejowiee:~$

**Comment by aristocratos** [comment]
> fatal: destination path 'bashtop' already exists and is not an empty directory.

I don't know how you interpret that error message, but did you try removing the directory?

You could also run `git pull` from the directory to update instead of cloning a new copy.

Try `man git` or read up on how git works at https://git-scm.com/docs/user-manual
