### ISSUE TITLE
Dirty color rendering with rxvt terminal...fixable?

### ISSUE THREAD

**Issue by CaptainBloodz** [aristocratos/bashtop#157]
cat ~/.Xdefaults
Xft.dpi:        96
Xft.antialias:  true
Xft.rgba:       rgb
Xft.hinting:    true
Xft.hintstyle:  hintslight
Xft.autohint:   false
Xft.lcdfilter:  lcddefault 

! rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
! options: perl,xft,styles,combining,blink,iso14755,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
! Usage: urxvt [options] [-e command args]
! 
! where resources (long-options) include:
!   termName:                       string
!   geometry:                       geometry
!   chdir:                          string
!   reverseVideo:                   boolean
!   loginShell:                     boolean
!   multiClickTime:                 number
!   jumpScroll:                     boolean
!   skipScroll:                     boolean
!   pastableTabs:                   boolean
!   scrollstyle:                    mode
!   scrollBar:                      boolean
!   scrollBar_right:                boolean
!   scrollBar_floating:             boolean
!   scrollBar_align:                mode
!   thickness:                      number
!   scrollTtyOutput:                boolean
!   scrollTtyKeypress:              boolean
!   scrollWithBuffer:               boolean
!   inheritPixmap:                  boolean
!   transparent:                    boolean
!   tintColor:                      color
!   shading:                        number
!   blurRadius:                     HxV
!   fading:                         number
!   fadeColor:                      color
!   utmpInhibit:                    boolean
!   urgentOnBell:                   boolean
!   visualBell:                     boolean
!   mapAlert:                       boolean
!   meta8:                          boolean
!   mouseWheelScrollPage:           boolean
!   tripleclickwords:               boolean
!   insecure:                       boolean
!   cursorUnderline:                boolean
!   cursorBlink:                    boolean
!   pointerBlank:                   boolean
!   background:                     color
!   foreground:                     color
!   color0:                         color
!   color1:                         color
!   color2:                         color
!   color3:                         color
!   color4:                         color
!   color5:                         color
!   color6:                         color
!   color7:                         color
!   color8:                         color
!   color9:                         color
!   color10:                        color
!   color11:                        color
!   color12:                        color
!   color13:                        color
!   color14:                        color
!   color15:                        color
!   colorBD:                        color
!   colorIT:                        color
!   colorUL:                        color
!   colorRV:                        color
!   underlineColor:                 color
!   scrollColor:                    color
!   troughColor:                    color
!   highlightColor:                 color
!   highlightTextColor:             color
!   cursorColor:                    color
!   cursorColor2:                   color
!   pointerColor:                   color
!   pointerColor2:                  color
!   borderColor:                    color
!   path:                           search path
!   backgroundPixmap:               file[;geom]
!   iconFile:                       file
!   pointerShape:                   string
!   font:                           fontname
!   boldFont:                       fontname
!   italicFont:                     fontname
!   boldItalicFont:                 fontname
!   intensityStyles:                boolean
!   inputMethod:                    name
!   preeditType:                    style
!   imLocale:                       string
!   imFont:                         fontname
!   title:                          string
!   iconName:                       string
!   saveLines:                      number
!   buffered:                       boolean
!   depth:                          number
!   visual:                         number
!   transient-for:                  windowid
!   override-redirect:              boolean
!   hold:                           boolean
!   externalBorder:                 number
!   internalBorder:                 number
!   borderLess:                     boolean
!   lineSpace:                      number
!   letterSpace:                    number
!   skipBuiltinGlyphs:              boolean
!   pointerBlankDelay:              number
!   backspacekey:                   string
!   deletekey:                      string
!   print-pipe:                     string
!   modifier:                       modifier
!   cutchars:                       string
!   answerbackString:               string
!   secondaryScreen:                boolean
!   secondaryScroll:                boolean
!   perl-lib:                       string
!   perl-eval:                      perl-eval
!   perl-ext-common:                string
!   perl-ext:                       string
!   iso14755:                       boolean
!   iso14755_52:                    boolean
!   xrm:                            string
!   keysym.sym:                     keysym
!   background.border:              boolean
!   background.expr:                string
!   background.interval:            seconds
!   bell-command:                   string
!   font-size.step:                 interger
!   kuake.hotkey:                   string
!   matcher.button:                 string
!   matcher.launcher:               string
!   matcher.launcher.*:             string
!   matcher.pattern.*:              string
!   matcher.rend.*:                 string
!   remote-clipboard.fetch:         string
!   remote-clipboard.store:         string
!   searchable-scrollback:          string
!   selection-autotransform.*:      string
!   selection-pastebin.cmd:         string
!   selection-pastebin.url:         string
!   selection.pattern-0:            string
!   tab-bg:                         colour
!   tab-fg:                         colour
!   tabbar-bg:                      colour
!   tabbar-fg:                      colour
!   url-launcher:                   string

!
!
!

!   termName:                       string
!   geometry:                       geometry
!   chdir:                          string
URxvt.reverseVideo:                 true
!   loginShell:                     boolean
!   multiClickTime:                 number
!   jumpScroll:                     boolean
!   skipScroll:                     boolean
!   pastableTabs:                   boolean
URxvt.scrollstyle:                  rxvt !likely defaulted to plain
!   scrollBar:                      boolean !true by default
URxvt.scrollBar_right:              true
!   scrollBar_floating:             boolean
!   scrollBar_align:                mode
!   thickness:                      number
URxvt.scrollTtyOutput:              false
URxvt.scrollTtyKeypress:            true
URxvt.scrollWithBuffer:             true
!   inheritPixmap:                  boolean
!   transparent:                    boolean
!   tintColor:                      color
!   shading:                        number
!   blurRadius:                     HxV
!   fading:                         number
!   fadeColor:                      color
!   utmpInhibit:                    boolean
!   urgentOnBell:                   boolean
!   visualBell:                     boolean
!   mapAlert:                       boolean
!   meta8:                          boolean
!   mouseWheelScrollPage:           boolean
!   tripleclickwords:               boolean
!   insecure:                       boolean
!   cursorUnderline:                boolean
URxvt.cursorBlink:                  true
!   pointerBlank:                   boolean
!   background:                     color
!   foreground:                     color
!black #000000
!   color0:                         color
!maroon #A80000
!   color1:                         color
!green #00A800
!   color2:                         color
!olive #A8A800
!   color3:                         color
!navy #0000A8
!   color4:                         color
!purple #A800A8
!   color5:                         color
!teal #00A8A8
!   color6:                         color
!silver #A8A8A8
!   color7:                         color
!grey #000054
!   color8:                         color
!red #FF0054
!   color9:                         color
!lime #00FF54
!   color10:                        color
!yellow #FFFF54
!   color11:                        color
!blue #0000FF
!   color12:                        color
 *.color12:                          #3465A4
!fuschia #FF00FF 
!   color13:                        color
!aqua #00FFFF
!   color14:                        color
!white #FFFFFF
!   color15:                        color

!   colorBD:                        color
!   colorIT:                        color
!   colorUL:                        color
!   colorRV:                        color
!   underlineColor:                 color
URxvt.scrollColor:                  olive
!   troughColor:                    color
!   highlightColor:                 color
!   highlightTextColor:             color
!   cursorColor:                    color
!   cursorColor2:                   color
!   pointerColor:                   color
!   pointerColor2:                  color
!   borderColor:                    color
!   path:                           search path
!   backgroundPixmap:               file[;geom]
!   iconFile:                       file
!   pointerShape:                   string
URxvt.font:                         xft:RobotoMono Nerd Font:medium:pixelsize=14
URxvt.boldFont:                     xft:RobotoMono Nerd Font:bold:pixelsize=14
URxvt.italicFont:                   xft:RobotoMono Nerd Font:italic:pixelsize=14
URxvt.boldItalicFont:               xft:RobotoMono Nerd Font:bold:italic:pixelsize=14
!   intensityStyles:                boolean
!   inputMethod:                    name
!   preeditType:                    style
!   imLocale:                       string
!   imFont:                         fontname
!   title:                          string
!   iconName:                       string
URxvt.saveLines:                    100000
!   buffered:                       boolean
!   depth:                          number
!   visual:                         number
!   transient-for:                  windowid
!   override-redirect:              boolean
!   hold:                           boolean
!   externalBorder:                 number
!   internalBorder:                 number
!   borderLess:                     boolean
!   lineSpace:                      number
!   letterSpace:                    number
!   skipBuiltinGlyphs:              boolean
!   pointerBlankDelay:              number
!   backspacekey:                   string
!   deletekey:                      string
!   print-pipe:                     string
!   modifier:                       modifier
!   cutchars:                       string
!   answerbackString:               string
!   secondaryScreen:                boolean
!   secondaryScroll:                boolean
!   perl-lib:                       string
!   perl-eval:                      perl-eval
URxvt.perl-ext-common:              default,matcher,resize-font,tabbed
!   perl-ext:                       string
!   iso14755:                       boolean
!   iso14755_52:                    boolean
!   xrm:                            string
!   keysym.sym:                     keysym
!   background.border:              boolean
!   background.expr:                string
!   background.interval:            seconds
!   bell-command:                   string
!   font-size.step:                 interger
!   kuake.hotkey:                   string
!   matcher.button:                 string
!   matcher.launcher:               string
!   matcher.launcher.*:             string
!   matcher.pattern.*:              string
!   matcher.rend.*:                 string
!   remote-clipboard.fetch:         string
!   remote-clipboard.store:         string
!   searchable-scrollback:          string
!   selection-autotransform.*:      string
!   selection-pastebin.cmd:         string
!   selection-pastebin.url:         string
!   selection.pattern-0:            string
!   tab-bg:                         colour
!   tab-fg:                         colour
!   tabbar-bg:                      colour
!   tabbar-fg:                      colour
!   url-launcher:                   string

! Not found in -help!

!FONTS
!URxvt.perl-ext-common: font-size
URxvt.keysym.C-Up:     font-size:increase
URxvt.keysym.C-Down:   font-size:decrease
URxvt.keysym.C-S-Up:   font-size:incglobal
URxvt.keysym.C-S-Down: font-size:decglobal
URxvt.keysym.C-equal:  font-size:reset

URxvt.keysym.C-Up:        resize-font:smaller
URxvt.keysym.C-Down:      resize-font:bigger
URxvt.keysym.C-equal:     resize-font:reset
URxvt.keysym.C-question:  resize-font:show

!URL-SELECT
!URxvt.perl-ext: default,url-select
!NOMOUSE
URxvt.url-launcher: /usr/bin/xdg-open
-----------------------------------------------------
Any experience to share in this respect?
Thls 4 ur attention, interest & support.

**Comment by aristocratos** [comment]
> For correct display, a terminal with support for:
> 
>     24-bit truecolor
>     Wide characters
