### ISSUE TITLE
[BUG] Bashtop not running without cpufreq

### ISSUE THREAD

**Issue by Thaolia** [aristocratos/bashtop#16]
**Describe the bug**
Bashtop not running on OVH VPS. The problem is about cpufreq part.

**To Reproduce**
Run bashtop on linux without cpufreq module loaded.

**Info (please complete the following information):**
- Last Ubuntu 16.04
- OVH VPS

Log :
New instance of bashtop version: 0.8.4 Pid: 21402
09:18:30 PM ERROR: On line 724 
09:18:30 PM ERROR: On line 724 (MUTED!)
./bashtop: line 669: /sys/devices/system/cpu/cpu-1/cpufreq/scaling_cur_freq: No such file or directory
09:18:37 PM ERROR: On line 669 
09:18:37 PM ERROR: On line 682 
09:18:37 PM ERROR: On line 724 
09:18:37 PM ERROR: On line 724 (MUTED!)
./bashtop: line 1413: mem[available]*100/mem[total]: division by 0 (error token is "mem[total]")
./bashtop: line 669: /sys/devices/system/cpu/cpu-1/cpufreq/scaling_cur_freq: No such file or directory
09:18:38 PM ERROR: On line 669 
09:18:38 PM ERROR: On line 682 
./bashtop: line 914: local: `': not a valid identifier
09:18:38 PM ERROR: On line 914 
./bashtop: line 914: local: `': not a valid identifier
09:18:38 PM ERROR: On line 914 (MUTED!)
./bashtop: line 914: local: `': not a valid identifier
./bashtop: line 914: local: `': not a valid identifier
./bashtop: line 1565: ( ( 32372130-32371881 ) * 1000 * 1000 ) / ( cpu[hz]*time_elapsed*cpu[threads] ) : division by 0 (error token is "( cpu[hz]*time_elapsed*cpu[threads] ) ")

**Comment by aristocratos** [comment]
Missing cpu frequency error handling fixed and will be in next update.
However you left out bash version which for Ubuntu 16.04 is bash 4.3-14
Bash 4.4 is required and a couple of your errors looks to be related to that.

**Comment by Thaolia** [comment]
Thanks ! Okay for bash 4.4.

I keep open this ticket for your PR/commit. 

Many thanks for your application !

**Comment by aristocratos** [comment]
Fixed in [7e484aa](https://github.com/aristocratos/bashtop/commit/7e484aacb13f37391c09e2fa81549cf1279cf558)
