### ISSUE TITLE
[BUG] No color in nvim terminal

### ISSUE THREAD

**Issue by Rizhiy** [aristocratos/bashtop#160]
**Describe the bug**
When running inside nvim terminal (`:term`) bashtop doesn't have color. The rest of the terminal and other programs (e.g. htop, ytop) use colors properly.

**To Reproduce**

Install vim, run terminal `:term`, run bashtop

**Expected behavior**

Bashtop with color

**Screenshots**
![image](https://user-images.githubusercontent.com/5617397/86520823-566f8900-be51-11ea-9704-d1e47135a15e.png)
**Info (please complete the following information):**
 - Bashtop version: 0.9.19
 - (Linux) Linux distribution and version:
 - (Linux) Data collection type (/proc or psutil):
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Vim terminal
 - Font used:
 - Bash version, "bash --version" (version 4.4 or above is required):
 - Locales: output of "locale -v"

**Additional context**

contents of `$HOME/.config/bashtop/error.log`

(enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing)

**Comment by aristocratos** [comment]
I would suggest you report this to nvim and not here. The colors are set with ANSI escape codes, if they don't work it's the terminal you are using that fails to interpret the escape codes.

**Comment by Rizhiy** [comment]
Colors work in every other program (htop, ytop, terminal itself, e.g.), pretty sure this is your bug.

**Comment by aristocratos** [comment]
Neither htop or ytop uses 24-bit color. There is literally nothing I can do here, I can't change how [ANSI Codes](https://en.wikipedia.org/wiki/ANSI_escape_code) work...

**Comment by Rizhiy** [comment]
Maybe add an option for 8-bit color?

**Comment by aristocratos** [comment]
https://github.com/neovim/neovim/issues/2571
The script is optimized for 24-bit color and says so pretty clearly in the readme:

> For correct display, a terminal with support for:
> 
>     24-bit truecolor
>     Wide characters

It would be pretty big rewrite to include 8-bit colors support now just for a few corner cases of terminals not supporting truecolor.
So I will not spend time on it at this point. But anybody is free to do it them self and open a pull request.
