### ISSUE TITLE
[BUG] insecure use of /tmp

### ISSUE THREAD

**Issue by daissi** [aristocratos/bashtop#161]
Forward of a [Debian bug report](https://bugs.debian.org/964366)

**Describe the bug**

bashtop creates a Python script in /tmp and runs it. But Python adds the 
directory containing the script to the module search path¹, and /tmp is 
world-writable, so this in insecure. A local user could plant malicious 
Python module in /tmp, which would be executed by bashtop.

**To Reproduce**

Create a psutil.py file with:
`import os; os.system('(tput reset && cowsay pwned) >/dev/tty; kill -ABRT %s' % os.getppid())`

```
  $ install -m 644 /path/to/psutil.py /tmp
  $ bashtop
   _______
  < pwned >
   -------
          \   ^__^
           \  (oo)\_______
              (__)\       )\/\
                  ||----w |
                  ||     ||
  Aborted
```

**Comment by aristocratos** [comment]
@daissi 
Huh, that's no good.

Could be solved by creating a randomly named folder and placing the script in right?

Don't know of a way of changing the search paths without first importing ´sys´ which could be hijacked in the same way I guess.

**Comment by aristocratos** [comment]
```bash
	pytmpdir=$(mktemp -d "${TMPDIR:-/tmp}"/XXXXXXXXXXXX)
	pywrapper=$(mktemp "${pytmpdir}"/bashtop.psutil.XXXX)
```
Should fix the issue.

**Comment by daissi** [comment]
Hi Jakub,

Le lun. 6 juil. 2020 à 13:29, aristocratos <notifications@github.com> a écrit :
>
> pytmpdir=$(mktemp -d "${TMPDIR:-/tmp}"/XXXXXXXXXXXX)
> pywrapper=$(mktemp "${pytmpdir}"/bashtop.psutil.XXXX)
>
> Should fix the issue.
>

Does the proposed fix by upstream look good to you?

Best,
Dylan

**Comment by daissi** [comment]
* Dylan Aïssi <daissi@debian.org>, 2020-07-06, 15:13:
>>pytmpdir=$(mktemp -d "${TMPDIR:-/tmp}"/XXXXXXXXXXXX)
>>pywrapper=$(mktemp "${pytmpdir}"/bashtop.psutil.XXXX)
>>
>>Should fix the issue.
>
>Does the proposed fix by upstream look good to you?

It's mostly OK, but:
- mktemp(1) can fail, and this failure should not be ignored;
- there's no need for two mktemp calls.

Something like this should work:

   pytmpdir=$(mktemp -d "${TMPDIR:-/tmp}"/bashtop.XXXXXX) || exit 1
   pywrapper=${pytmpdir}/psutil

-- 
Jakub Wilk

**Comment by aristocratos** [comment]
Will make suggested changes in next update.

**Comment by aristocratos** [comment]
Changed to:
```bash
	if ! pytmpdir=$(mktemp -d "${TMPDIR:-/tmp}"/XXXXXXXXXXXX); then
		if [[ $system == "Linux" ]]; then
			use_psutil="false"
		else
			echo "ERROR: Failed setting up temp directory for psutil script!"
			exit 1
		fi
	else
		pywrapper="${pytmpdir}/bashtop.psutil"
	fi
```
