### ISSUE TITLE
[BUG] theme location

### ISSUE THREAD

**Issue by alcir** [aristocratos/bashtop#162]
A theme is supposed to be placed in `$HOME/.config/bashtop/themes` or `$HOME/.config/bashtop/user_themes`
But actually, bashtop seems to look in `HOME/.config/bashtop`

**Comment by aristocratos** [comment]
How so?

```bash
get_themes() {
	local file
	theme_int=0
	themes=("Default")
	for file in "${config_dir}/themes"/*.theme; do
		file="${file##*/}"
		if [[ ${file} != "*.theme" ]]; then themes+=("themes/${file%.theme}"); fi
		if [[ ${themes[-1]} == "${color_theme}" ]]; then theme_int=${#themes[@]}-1; fi
	done
	for file in "${config_dir}/user_themes"/*.theme; do
		file="${file##*/}"
		if [[ ${file} != "*.theme" ]]; then themes+=("user_themes/${file%.theme}"); fi
		if [[ ${themes[-1]} == "${color_theme}" ]]; then theme_int=${#themes[@]}-1; fi
	done
}
```

**Comment by alcir** [comment]
If I set a theme in `~/.config/bashtop/bashtop.cfg`
`color_theme="default_black"`

Here:
```
    494         #* Check if theme set in config exists and source it if it does
    495         if [[ -n ${color_theme} && ${color_theme} != "Default" && -e "${config_dir}/${color_theme%.theme}.theme" ]]; th        en 
    496                 # shellcheck source=/dev/null
    497                 source "${config_dir}/${color_theme%.theme}.theme"
    498                 sourced=1
    499         else
    500                 color_theme="Default"
    501         fi
```

**Comment by aristocratos** [comment]
Ah, right. After the user_themes folder was added themes will be prefixed with either `themes/` or `user_themes/` depending on location, which makes it possible to have custom versions of the default themes in the `user_themes` directory.

Guess I forgot to change the config file comment to reflect that.

**Comment by aristocratos** [comment]
Guess I should also add a check that they are prefixed...

**Comment by alcir** [comment]
Oh, ok, so it is supposed to specify a prefix.
`color_theme="themes/default_black"`

Ok. Thanks.

**Comment by aristocratos** [comment]
Yeah, but that's all done for you if you do it through the the config menu in bashtop instead of manually.

**Comment by alcir** [comment]
Makes sense. Thanks.

**Comment by aristocratos** [comment]
Np, thanks for bringing it up so I got reminded to add checks :)
