### ISSUE TITLE
[BUG] Arrow Keys unresponsive

### ISSUE THREAD

**Issue by JonA-01** [aristocratos/bashtop#163]
**Describe the bug**

Arrow keys are unreponsive within bashtop. The only possible way I can input up or down is with TAB and SHIFT+TAB respectively. Left and Right inputs are not possible at all. It's still possible to scroll through the process list, but it is impossible to change any option parmaeters in the option menu.

**To Reproduce**

Simply run `bashtop` and attempt to press the arrow keys to scroll though the process list

**Expected behavior**

The arrow keys will work as intended (i.e Scroll through the process list and options page, as well as, change option parameters)

**Info:**
 - Bashtop version: 0.9,18
 - Linux distribution and version: Kali 2020.2: 5.6.0-kali2-amd64
 - Data collection type (/proc or psutil): psutil 
 - Terminal used: konsole
 - Font used: Fira Code: 9pt
 - Bash version: 5.0.16(1)-release (x86_64-pc-linux-gnu)
 - Locales:

LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=

**Additional context**

I verified that the issue is only relating to `bashtop` as I ran `htop` and was able to use the arrow keys fine. 

contents of `$HOME/.config/bashtop/error.log`:
New instance of bashtop version: 0.9.18 Pid: 105515
 
New instance of bashtop version: 0.9.18 Pid: 110371
 
New instance of bashtop version: 0.9.18 Pid: 117702
/usr/bin/bashtop: line 2220: ((: (high: missing `)' (error token is "high")
/usr/bin/bashtop: line 2239: 0:: syntax error in expression (error token is ":")
 
New instance of bashtop version: 0.9.18 Pid: 118997
 
New instance of bashtop version: 0.9.18 Pid: 128232
 
New instance of bashtop version: 0.9.18 Pid: 129655
 
New instance of bashtop version: 0.9.18 Pid: 132857
 
New instance of bashtop version: 0.9.18 Pid: 142012
 
New instance of bashtop version: 0.9.18 Pid: 174843
13:32:22 ERROR: On line 720 
/usr/bin/bashtop: line 4814: ${pycoproc[1]}: ambiguous redirect
 
New instance of bashtop version: 0.9.18 Pid: 175660
 
New instance of bashtop version: 0.9.18 Pid: 176017
 
New instance of bashtop version: 0.9.18 Pid: 178190
 
New instance of bashtop version: 0.9.18 Pid: 178345
 
New instance of bashtop version: 0.9.18 Pid: 183604

**Comment by aristocratos** [comment]
What type of keyboard and what keyboard layout do you use? Any difference if you switch keyboard or keyboard layout? Any custom bindings in your dot files?
Any difference if you switch terminal? And could you also try creating a new user and see if get the same problem with a clean user profile?

Can't find any alternative escape codes for the arrow keys so have a hard time figuring why they wouldn't get picked up.

**Comment by aristocratos** [comment]
If you don't mind you can download the following script to test keyboard input:
[keytest.sh](https://gist.github.com/aristocratos/8a313f3b65cb0a9ad99d001fec5e6726)
Just run with `bash keytest.sh`, press the arrow keys and see what output you get and then quit with "q" or "ctrl+c".

**Comment by JonA-01** [comment]
I'm currently using my 2015 Macbook Pro to run linux (Single Boot) and not using an external keyboard but the laptop itself. The keyboard is in `US english Layout`. I don't use any custom bindings either. I've tried using xterm to run bashtop but it has the same result. Making a new user didn't fix the problem either. I forgot to mention this earlier, and I'm not sure if it will make a difference, but I'm running z-shell instead of normal shell.

I also ran keytest.sh and got the output: 

> Keypress = OA
> Keypress = OA
> Keypress = OA
> Keypress = OA
> Keypress = OD
> Keypress = OD
> Keypress = OD
> Keypress = OD
> Keypress = OB
> Keypress = OB
> Keypress = OB
> Keypress = OB
> Keypress = OC
> Keypress = OC
> Keypress = OC
> Keypress = OC

I pressed `Up` 4 times, `Left` 4 times, `Down` 4 times, and `Right` 4 times - In that order.

**Comment by aristocratos** [comment]
Ok, I think I figured it out, either z-shell or some shell init script is putting your terminal in "application cursor mode" which changes the keys to "OA OD OB OC".

I've added a line to keytest.sh that changes mode to regular cursor mode, would you mind re-downloading and test again.
[keytest.sh](https://gist.github.com/aristocratos/8a313f3b65cb0a9ad99d001fec5e6726)

**Comment by aristocratos** [comment]
I will add support for the "application cursor mode" in next update.
Until then it should work if you start bashtop with the command `echo -en "\033[?1l"; bashtop`

**Comment by JonA-01** [comment]
Thanks for that. It works great now! Thanks for your help. 
Great program btw. It's a lot more pleasing than htop HAHA.

**Comment by aristocratos** [comment]
No problem, and thanks :)
I will update this issue when I release the next update with the fix.

**Comment by aristocratos** [comment]
@JonA-01 
Fixed in v0.9.21
