### ISSUE TITLE
Weird Highlighting Makes it Hard to Read on Mac

### ISSUE THREAD

**Issue by parkingthought** [aristocratos/bashtop#165]
**Describe the bug**

The highlights applied to the text/interface make it difficult to read

**To Reproduce**

Install instructions used on MAC. Then resized for better visibility.

**Expected behavior**

No highlights obscuring the lovely graphs etc.

**Screenshots**

Attach.

**Info (please complete the following information):**
 - Bashtop version: - (OSX/FreeBSD) Os release version: Catalina
 - Terminal used: bash and zsh
 - Font used: DejaVu Sans
![Screen Shot 2020-07-09 at 14 35 56](https://user-images.githubusercontent.com/2872770/87088590-47425f80-c1f2-11ea-9da2-406cf68ba194.png)

**Comment by parkingthought** [comment]
#firstbugever Let me know if I did it correctly. This looks super cool and I'd love to get it so I can use it on Mac.

**Comment by aristocratos** [comment]
> Compatibility
> 
> Should work on most modern linux distributions, on Mac OS X and on FreeBSD.
> 
> Will not display correctly on the standard terminal on OSX! Recommended alternative iTerm2
> 
> Will also need to be run as superuser on OSX to display stats for processes not owned by user.
> 
> The disk io stats on OSX and FreeBSD shows iostats for all disks at the top instead of per disk.

**Comment by parkingthought** [comment]
Oh my goodness this app looks absolutely amazing in iTerm2! Thank you for teaching me something new. I hope my filing a bug wasn't too big of a distraction from your other work.

**Comment by aristocratos** [comment]
No problem mate :) No worries about reporting bugs, I just wish people took a little time reading the readme since many visual problems can be fixed by looking through the Compatibility section.

**Comment by parkingthought** [comment]
Yeah, I’m sorry I didn’t think to go there. I would have totally seen a note under the MacOS prerequisites though.

Something like this around line 207:


NOTE: The default Mac Terminal adds artifacts to the display. Alternative terminals such as [iTerm2](https://iterm2.com) should be considerened in order for it to render properly in MacOS.

Either way this thing is the bomb diggity!

Thank you again!

**Comment by aristocratos** [comment]
Good idea. Could possibly rename the compatibility section to prerequisites and have a subsection for each OS to bring some more attention to it.

**Comment by paulrobichaud** [comment]
> Yeah, I’m sorry I didn’t think to go there. I would have totally seen a note under the MacOS prerequisites though.
> 
> Something like this around line 207:
> 
> 
> NOTE: The default Mac Terminal adds artifacts to the display. Alternative terminals such as [iTerm2](https://iterm2.com) should be considerened in order for it to render properly in MacOS.
> 
> Either way this thing is the bomb diggity!
> 
> Thank you again!
> […](#)

I just tested it in [Warp](https://www.warp.dev/) terminal - it works well there as well.
