### ISSUE TITLE
[BUG] loads Python modules from cwd

### ISSUE THREAD

**Issue by daissi** [aristocratos/bashtop#167]
Forward of another [Debian security bug report](https://bugs.debian.org/964788) by Jakub Wilk
(This is similar to https://github.com/aristocratos/bashtop/issues/161, but less severe.)

**Describe the bug**

bashtop runs

`python3 -c "import psutil"`

to check if the psutil module is available.

But when you use -c, Python adds the current working directory to the 
module search path¹. As consequence, you can't run bashtop securely when 
your cwd is untrusted (e.g. /tmp).

I suggest changing the command in question to:

`(cd / && python3 -c "import psutil")`

¹ https://docs.python.org/3/using/cmdline.html#cmdoption-c

**Comment by aristocratos** [comment]
Will fix in next update.

**Comment by aristocratos** [comment]
Fixed in v0.9.22
