### ISSUE TITLE
bashtop can't kill selected process mac os

### ISSUE THREAD

**Issue by SmithJson** [aristocratos/bashtop#168]
I press K or k to kill the process, but nothing happens

System
![image](https://user-images.githubusercontent.com/40036121/87219040-a044fb80-c38a-11ea-8afd-e754e29075df.png)

output
![image](https://user-images.githubusercontent.com/40036121/87219085-fb76ee00-c38a-11ea-9129-07c16d2f7611.png)

**Comment by aristocratos** [comment]
Follow the bug report template or I can't help you.

**Comment by SmithJson** [comment]
> Follow the bug report template or I can't help you.

![image](https://user-images.githubusercontent.com/40036121/87241182-1319a980-c453-11ea-8360-83d2fbff9373.png)

**Comment by aristocratos** [comment]
Will be fixed in next version.

**Comment by aristocratos** [comment]
@SmithJson 
Fixed in v0.9.23

**Comment by SmithJson** [comment]
> @SmithJson
> Fixed in v0.9.23

Thanks
