### ISSUE TITLE
[REQUEST] add iotop stats

### ISSUE THREAD

**Issue by garanews** [aristocratos/bashtop#17]
**Describe the solution you'd like**
It would be useful integrate also I/O stats, like iotop:

**Additional context**

![image](https://user-images.githubusercontent.com/16938405/80183349-f4043c00-8608-11ea-8687-9d0bf1b510fb.png)

**Comment by aristocratos** [comment]
Will integrate into psutil version since psutil has a function for disk io, so will be added in a couple of weeks.

**Comment by aristocratos** [comment]
Added in v0.8.19

**Comment by oersted** [comment]
Where is it supposed to show I/O stats for disks? I can only see Used/Free in the disks section with v0.9.25. I definitely have iostat and sysstat installed. I tried with and without psutil, but nothing.

Maybe I am missing it, could you send a screenshot of how the Read/Write stats are supposed to look?
