### ISSUE TITLE
[REQUEST] Option to use 24-hour clock

### ISSUE THREAD

**Issue by UserBlackBox** [aristocratos/bashtop#172]
**Describe the solution you'd like**
An option in the menu to set the clock to display 24-hour time

**Comment by aristocratos** [comment]
Huh?

![Screenshot at 2020-07-19 23-26-54](https://user-images.githubusercontent.com/59659483/87885666-b05a7c00-ca17-11ea-87d6-519868a84ab1.png)

**Comment by UserBlackBox** [comment]
Shoot didn't see that

**Comment by aristocratos** [comment]
No worries :)
