### ISSUE TITLE
[BUG] bashtop hangs at "Running mem collection init" in Crostini container

### ISSUE THREAD

**Issue by bolapara** [aristocratos/bashtop#173]
**Describe the bug**

When launching bashtop in a Crostini (Linux containers on ChromeOS) container, it hangs at "Running mem collection init" step.

**To Reproduce**

Launch bashtop in default debian container on ChromeOS

**Info (please complete the following information):**
 - Bashtop version: v0.9.24
 - (Linux) Linux distribution and version: Debian 10 in Crostini.  ChromeOS version 83.0.4103.119
 - (Linux) Data collection type (/proc or psutil): /proc
 - Psutil version: 5.7.2
 - Terminal used: 
 - Font used:
 - Bash version, 5.0.3
 - Locales: output of `locale -v`

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Additional context**

Debugging shows it seems to be hanging while trying to set iostat_var, presumably because dev_path is empty.

contents of `$HOME/.config/bashtop/error.log`

New instance of bashtop version: 0.9.24 Pid: 9640
11:47:37 AM ERROR: On line 2272

**Comment by bolapara** [comment]
#171 is the PR to fix

**Comment by aristocratos** [comment]
Just to clarify, does it work as expected when using `psutil` instead of `/proc`?

Also what info do you get about the 9p partition in question from `df`?

Is there a need to have the partition listed with the rest of disks? In that case I could probably find a way of excluding it from the iostat check instead of excluding it from being discovered at all.

**Comment by bolapara** [comment]
Seems to work fine with psutil, but I don't see the filesystem listed in the "disks" section so not sure how psutil is handling that filesystem type.

```
bolapara@penguin:~$ df -t 9p
Filesystem     1K-blocks  Used Available Use% Mounted on
9p               4014004   752   4013252   1% /mnt/chromeos

bolapara@penguin:~$ grep 9p /proc/mounts 
9p /mnt/chromeos 9p rw,sync,dirsync,nosuid,nodev,noexec,relatime,access=any,trans=fd,rfd=26,wfd=26 0 0
```

I had previously understood that the 9P filesystem was a mechanism for the VM and the containers to communicate with the host OS.  The filesystem is mounted rw but none of the directories in there are writable by the container, not even as root.  If I run a 'find' in that filesystem, all I see are font files.  However, I found that if you share a directory from ChromeOS with the Linux container, that folder appears in that 9P filesystem and is writable.  After sharing the directory with the container, the total/used/available blocks counts listed by 'df' do not change significantly nor do they seem to make sense with the block counts from the host system.  So it seems to me that this filesystem space isn't one that a user can really directly affect so I question the usefulness of collecting 'df' info for that filesystem.  I suppose it could be useful for debugging purposes if whatever process manages that filesystem has problems but I think that sounds like an edge case.

**Comment by aristocratos** [comment]
I would guess psutil is detecting the fileystem as a pseudo fileystem and excluding by default then when passed the `all=False` flag. So your fix seems like a good choice for `/proc` and `psutil` methods to work the same. 

I should probably look through the psutil source for more filesystems excluded by default and add them to `df` excludes.

**Comment by valp124** [comment]
I have the same problem on `Ubuntu` `bionic`, even with `psutil`. The interesting thing is that I have another system that's nearly identical, and it works fine there. 

Another thing is that if I hit `ctrl-c` while it hangs six times (no more, no less), it goes through, draws the screen momentarily with all the information, and then quits.

`error.log` says:

```
New instance of bashtop version: 0.9.25 Pid: 861
03:06:38 PM ERROR: On line 2271
03:06:41 PM ERROR: On line 2271 (MUTED!)
```

**Comment by aimana007** [comment]
I am having this problem (with psutil) on my desktop as well. It's been gobbling up 1 core for the last 20 minutes trying to count RAM.
_The problem does NOT happen when firing bashtop as root._
System is 96 core, 396GB ram
![bug](https://user-images.githubusercontent.com/1709028/157975459-b3f3695d-d40c-44b2-a0f3-896b27990705.png)
.

**Comment by nephewtom** [comment]
I am having exactly the same issue with a Rocky Linux box with` /proc`:

```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

> I have the same problem on `Ubuntu` `bionic`, even with `psutil`. The interesting thing is that I have another system that's nearly identical, and it works fine there.
> 
> Another thing is that if I hit `ctrl-c` while it hangs six times (no more, no less), it goes through, draws the screen momentarily with all the information, and then quits.
> 
> `error.log` says:
> 
> ```
> New instance of bashtop version: 0.9.25 Pid: 861
> 03:06:38 PM ERROR: On line 2271
> 03:06:41 PM ERROR: On line 2271 (MUTED!)
> ```

**Comment by eduard-neufeld-ssv** [comment]
same problem here on Debian 10, installed from debian `apt-get install bashtop`. Same with `psutil` enabled.
```
New instance of bashtop version: 0.9.25 Pid: 18847
13:27:33 ERROR: On line 2271.
13:27:33 ERROR: On line 2271 (MUTED!)
```
