### ISSUE TITLE
Some Tiling/sizing are sliding

### ISSUE THREAD

**Issue by K4S1** [aristocratos/bashtop#178]
![image](https://user-images.githubusercontent.com/8589819/89382250-d7dd6400-d6fa-11ea-9465-1c216e8c5614.png)
![image](https://user-images.githubusercontent.com/8589819/89382307-ec216100-d6fa-11ea-844f-8785316cd51f.png)
![image](https://user-images.githubusercontent.com/8589819/89382622-71a51100-d6fb-11ea-8bad-d5ae293311a6.png)

Bashtop Version 0.9.24

OS: ArcoLinux 
Kernel: 5.7.3-arch1-1 
Shell: bash 5.0.17 
Resolution: 2560x1440, 2560x1440, 2560x1440 
DE: Plasma 5.19.4 
Terminal: konsole 
Terminal Font: Noto Sans Mono 10

**Comment by TheLazyist** [comment]
I have the same issue I havent figured out the how to solve the issue just yet!

**Comment by K4S1** [comment]
Update on this:
I see that v. 0.9.25 have fixed this.
But See that The % are not listed each CPU Core is this intended ?
![image](https://user-images.githubusercontent.com/8589819/93593467-76283f00-f9b4-11ea-8bc2-18cda8ab656a.png)

![image](https://user-images.githubusercontent.com/8589819/93593420-5db82480-f9b4-11ea-8c6d-65deb0fd228c.png)

**Comment by K4S1** [comment]
Okay I see that bashtop not really are being updated more.
Fair I move to bpytop see this is the Next level.

All seems fine here:
![image](https://user-images.githubusercontent.com/8589819/93594315-e5eaf980-f9b5-11ea-9025-26cc6c6c4514.png)

Thanks any way :)
Have a great one.
