### ISSUE TITLE
[BUG] Pause/Option menu incompatibilities with the French locale (?).

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [aristocratos/bashtop#18]
**Describe the bug**
Strange-looking output of the option/pause menu on yakuake.

**To Reproduce**
1. Use Yakuake to launch bashtop
2. Press Echap by default to activate the pause/option menu.
3. Notice that it render the output pretty weirdly.

**Expected behavior**
Correctly displayed ASCII menu entries.
The darkening background isn’t showing up the same as displayed on the screenshot as well, but I don’t consider it as an issue.

**Screenshots**
![Peek 2020-04-24 12-19](https://user-images.githubusercontent.com/13170204/80202512-093b9380-8626-11ea-9866-535b2b5535ca.png)
(Ignore the flickering at the top, It’s due to the https://github.com/phw/peek capture. I don’t know what to use for recording things like I was doing with ShareX before)

**Info (please complete the following information):**
- Linux distribution and version
```❯ neofetch
                   -`                    pm@VIX
                  .o+`                   ------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Kernel: 5.6.6-13-tkg-bmq
               `+oooooo:                 Uptime: 3 hours, 33 mins
               -+oooooo+:                Packages: 1943 (pacman)
             `/:-:++oooo+:               Shell: bash 5.0.16
            `/++++/+++++++:              Resolution: 3440x1440
           `/++++++++++++++:             DE: Plasma
          `/+++ooooooooooooo/`           WM: KWin
         ./ooosssso++osssssso+`          WM Theme: Layan
        .oossssso-````/ossssss+`         Theme: Layan [Plasma], Layan-dark [GTK2/3]
       -osssssso.      :ssssssso.        Icons: korla [Plasma], korla [GTK2/3]
      :osssssss/        osssso+++.       Terminal: yakuake
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce GTX 1060 6GB
  `+sso+:-`                 `.-/+oso:    Memory: 8369MiB / 32044MiB
 `++:.                           `-/+/
 .`                                 `/

```
- System locale (output of “echo $LANG”)
`fr_FR.UTF-8` (us_US.UTF-8 also installed on my computer, for compatibility reasons)

- Bash version
```
1 core/bash 5.0.016-1 (1.6 MiB 8.0 MiB) (Installed)
    The GNU Bourne Again shell
```

**Out of topic notes**
Discovered your resource monitor via one article of the [NextInpact french news website](https://www.nextinpact.com/brief/bashtop---un-impressionnant-moniteur-de-ressources-systemes-en-bash-12146.htm), I absolutely love it!

**Comment by PoorPocketsMcNewHold** [comment]
Well, After testing with other terminal applications, I noticed that it happened with other terminals too so... It is maybe something to do with the system locale ?
Guake.
![Guake](https://user-images.githubusercontent.com/13170204/80204324-f6768e00-8628-11ea-984b-cea31a5761eb.png)
Konsole.
![Konsole](https://user-images.githubusercontent.com/13170204/80204328-f8405180-8628-11ea-9e53-af266ff61345.png)
Tilda.
![Tilda](https://user-images.githubusercontent.com/13170204/80204330-f9717e80-8628-11ea-8343-ac6f40f1b8b2.png)

**Comment by aristocratos** [comment]
Have you tried with other fonts? Looks like the symbols for the banner is wrong.

**Comment by PoorPocketsMcNewHold** [comment]
> Have you tried with other fonts? Looks like the symbols for the banner is wrong.

![FontHackYakuake](https://user-images.githubusercontent.com/13170204/80213800-064a9e00-863a-11ea-90af-937389ed0652.png)
Tested here with the Hack font.
Also tried with Consolas and Fire Mono with no successful results (Also, no need to ask for the Yakuake transparency inconsistency, [It has been like that since a long time).](https://forum.manjaro.org/t/yakuake-background-transparency-works-blur-doesnt/57905)

**Comment by aristocratos** [comment]
Maybe related: https://bbs.archlinux.org/viewtopic.php?id=228764

**Comment by aristocratos** [comment]
Closing due to not seeming to be a problem with bashtop but a problem with incorrect set system locales.
