### ISSUE TITLE
[BUG] Unable to run bashtop on FreeBSD 12.1-p8 using Python 3.7.8

### ISSUE THREAD

**Issue by jakobbg** [aristocratos/bashtop#182]
**Describe the bug**

Unable to run bashtop on FreeBSD 12.1-p8 using Python 3.7.8

**To Reproduce**

```
$ bashtop
Error: Missing python3!
```

**Expected behavior**

bashtop displayed (was able to make this work on my Mac)

**Info (please complete the following information):**
 - Bashtop version: commit d2eb76ea5ba9ea98ed673d7bcec3c388b035aedc
 - Psutil version: `python3 -c "import psutil; print(psutil.version_info)"`: (5, 7, 2)
 - Os release version: FreeBSD 12.1-RELEASE-p8
 - Bash version: GNU bash, version 5.0.18(2)-release (amd64-portbld-freebsd12.1)
 - Locales: 
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE=C
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

**Additional context**

Error-logging enabled, but no log-file exists.

**Comment by jakobbg** [comment]
```
$ which python
$ which python3
$ which python3.7
/usr/local/bin/python3.7
$ python3.7 --version
Python 3.7.8
```

**Comment by aristocratos** [comment]
You bashtop as superuser? Might not have /usr/local in path in that case.

Also, try out https://github.com/aristocratos/bpytop the python port of bashtop.

**Comment by jakobbg** [comment]
Not running as root. Will try python port instead!
