### ISSUE TITLE
This isn't really a PR, not even an issue - but I've got a working snap for bashtop :)

### ISSUE THREAD

**Issue by kz6fittycent** [aristocratos/bashtop#192]
Hi there, 

I've got to say, I LOVE `bashtop` and I love it so much, I made a snap. 

Here's the link the `snapcraft.yaml`: https://github.com/kz6fittycent/bashtop/blob/master/snapcraft.yaml 

I am happy to keep maintaining this snap, as I've got ...many... and I'm used to my workflow in doing so. If you'd rather take care of it all in house, we can move the snap into your name via forum.snapcraft.io. 

Let me know how you'd like to proceed and thanks again!

**Comment by aristocratos** [comment]
See response in https://github.com/aristocratos/bpytop/issues/101
