### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by navotera** [aristocratos/bashtop#195]
Hello. 

I want to ask a question : 
Please tell me what the difference between the Byte and Bits on these images : 
![image](https://user-images.githubusercontent.com/1424851/94331418-bdd74800-fffe-11ea-984c-1fa5c81e4fe0.png)

**Comment by aristocratos** [comment]
I'm not sure if this a serious question. One is the speed in bits the other the speed in bytes.
If you're confused about the difference you could maybe try googling `bit vs byte`.
