### ISSUE TITLE
[BUG] Closes after a few seconds [Proxmox]

### ISSUE THREAD

**Issue by FlorianMifsud** [aristocratos/bashtop#20]
**Describe the bug**
Closes after a few seconds

**To Reproduce**
Rnn bashtop

**Info (please complete the following information):**
 - Linux distribution and version => Linux version 4.15.18-21-pve (build@pve) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #1 SMP PVE 4.15.18-48 (Fri, 20 Sep 2019 11:28:30 +0200) (CT Proxmox debian 9)
 - System locale (output of "echo $LANG") => C 
 - Bash version => GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)

**Additional context**
$HOME/.config/bashtop/error.log" (enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing) 
New instance of bashtop version: 0.8.4 Pid: 89374
10:59:27 ERROR: On line 1976 
10:59:27 ERROR: On line 1976 (MUTED!)
./bashtop: line 1317: ( 100*(3677863579281055702-3677863579281055702-3677863579280962350+3677863579280962350) ) / (3677863579281055702-3677863579281055702) : division by 0 (error token is "(3677863579281055702-3677863579281055702) ")

**Comment by aristocratos** [comment]
This is related to [Is it working on LXC](https://github.com/aristocratos/bashtop/issues/7)
Will add another error check in next update, but core issue is with /proc/stat being messed up.

**Comment by JordanCHW** [comment]
Same here, is this issue been solved? Or any workaround? thanks!
