### ISSUE TITLE
[REQUEST] Display disk IO

### ISSUE THREAD

**Issue by emiliopedrollo** [aristocratos/bashtop#204]
**Is your feature request related to a problem? Please describe.**
Disk usage is being displayed but not disk IO

**Describe the solution you'd like**
On the disks section, it would be nice to have reads and writes info (bytes and count) and also busy_time

**Describe alternatives you've considered**
Currently I use `atop` for the task but it's very polluted and it's hard to get the values in a glance.

**Additional context**
Those values are available on psutil: https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters

**Comment by aristocratos** [comment]
@emiliopedrollo 
![main-s](https://user-images.githubusercontent.com/59659483/102909504-59028100-4479-11eb-98e1-7cb11df0e7ee.png)

If it's not working for you make a bug report.

**Comment by aristocratos** [comment]
Just noticed this was posted in bashtop and not bpytop :/

So the solution for you: get https://github.com/aristocratos/bpytop
