### ISSUE TITLE
List all dependencies on README

### ISSUE THREAD

**Issue by Exagone313** [aristocratos/bashtop#21]
On README, it says that it only requires Bash, then tells it also requires `date` command on previous versions, which isn't a Bash builtin.

I looked for external commands and I found these dependencies:
* ncurses binaries (tput...), but these should be on any Linux distribution by default (required by bash package on Arch, "required" package on Debian, not so sure for Alpine though)
* GNU Coreutils (date...), for example busybox date ignores `%N` if that matters
* procps (ps) - for example it's clearly not compatible with busybox ps

There may be more.

**Comment by aristocratos** [comment]
Yeah, there are a couple more like sensors, df and so on. But I'm in the process of replacing most external commands with python psutil, to gather all dependencies to just bash, python3 and psutil. And honestly didn't think that it would be that many people using it already. But sure, can update dependecies list to whats needed with current version.

**Comment by SuperSandro2000** [comment]
I would actually prefer having df, sensors, etc installed instead of requiring python.

**Comment by aristocratos** [comment]
Listed missing dependencies in README.md
The psutil version will be in a separate branch, so non pythton version will continue to exist.
