### ISSUE TITLE
[BUG] (minor) some window size expressed as WxH, some as HxW

### ISSUE THREAD

**Issue by doegox** [aristocratos/bashtop#22]
E.g. starting bashtop on a slightly smaller window, I get
`current size: 23x80 need to be at least 80x25` 
while I expect to see
`current size: 80x23 need to be at least 80x25` 

And when resizing dynamically, the message box also uses HxW.

Better to stick to the more common WxH everywhere...

**Comment by aristocratos** [comment]
Hah, hadn't even noticed. Was supposed to be WxH everywhere.
Fixed.
