### ISSUE TITLE
[BUG] Periodic crash, macOS, exception in runner thread

### ISSUE THREAD

**Issue by alexhking** [aristocratos/bashtop#222]
**Describe the bug**

Periodic, but somewhat random crash running `btop` on macOS. Results in exit to prompt with one line error: `ERROR: Exception in runner thread -> Proc:: -> wstring_convert::from_bytes`

**To Reproduce**

1. Run `btop`
2. Wait. (There is no clear action or timing for the bug)

**Expected behavior**

Expect btop to stay open until quit.

**Screenshots**

Example terminal showing random times for crash:
![btop-errors](https://user-images.githubusercontent.com/25096/154820360-022e5334-f040-44e5-9f78-799a0f73a830.png)

**Info (please complete the following information):**
 - Bashtop version: 1.2.3
 - (OSX/FreeBSD) Os release version: 10.15.7
 - Terminal used: Hyper 3.2.0
 - Font used: Fira Code
 - Bash version, `bash --version` (version 4.4 or above is required): 5.1
 - Locales: output of `locale -v`:
 ```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Additional context**

contents of `$HOME/.config/bashtop/error.log`:

No errors generated.

**Comment by aristocratos** [comment]
@alexhking 
Since you are running [btop](https://github.com/aristocratos/btop) and not bashtop this should probably be posted in the issues for btop instead.
The issue should be fixed in the latest commits.

**Comment by alexhking** [comment]
@aristocratos My bad 😅 Thank you so much.
