### ISSUE TITLE
[REQUEST] release management ? 

### ISSUE THREAD

**Issue by tormath1** [aristocratos/bashtop#24]
**Is your feature request related to a problem? Please describe.**
currently, there is no release / no tag.

**Describe the solution you'd like**
it could be nice to make official release of bashtop version (at list with tags :relaxed: ) in order to ease the package managers support.

**Describe alternatives you've considered**
I can see that there is a AUR package but it's targetting only `git` version.

**Additional context**
this software is super cool

**Comment by aristocratos** [comment]
Added tag for latest version. I'm pretty new to github so all tips are appreciated!
Not sure what best way of handling releases is, since it's likely I will be putting up a lot of small fixes with only a couple of lines changed.

**Comment by tormath1** [comment]
welcome on Github so ! 
In this case, I could recommend you to to read this: https://semver.org/ and this https://keepachangelog.com/en/1.0.0/ just to get some theory about release management. 
Then you could check other OSS project to check how they are actually handling their releases.

**Comment by gwarf** [comment]
And [GitHub Actions](https://github.com/features/actions)/[Travis](https://docs.travis-ci.com/user/tutorial/)/[Circle CI](https://circleci.com/) can be very handy to do some automated testing (like with [ShellCheck](https://github.com/koalaman/shellcheck) and packaging on PR or when tagging a release.
They are all free for open source stuff and can even automatically attach rpm/debs/whatever to a release once it passed tests and was built successfully.

**Comment by mzpiggeeup1** [comment]
> **Is your feature request related to a problem? Please describe.**
> currently, there is no release / no tag.
> 
> **Describe the solution you'd like**
> it could be nice to make official release of bashtop version (at list with tags  ) in order to ease the package managers support.
> 
> **Describe alternatives you've considered**
> I can see that there is a AUR package but it's targetting only `git` version.
> 
> **Additional context**
> this software is super cool

**Comment by Calinou** [comment]
Speaking of CI, [shfmt](https://github.com/mvdan/sh) could also be used in continuous integration to ensure everyone uses the same code style.
