### ISSUE TITLE
[BUG] Load average view is clipped

### ISSUE THREAD

**Issue by pappabewar** [aristocratos/bashtop#29]
**Describe the bug**
The brand new load average feature clips through the right-hand side of my terminal back into the left

**To Reproduce**
Run bashtop with a CPU with many cores

**Expected behavior**
Load average view doesn't clip 

**Screenshots**
![image](https://user-images.githubusercontent.com/61059757/80280102-881ef200-8734-11ea-9812-80e3025b60b5.png)

**Info (please complete the following information):**
 - Debian 9
 - en_GB.utf8
 - GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)

**Comment by aristocratos** [comment]
fixed in v0.8.7

**Comment by pappabewar** [comment]
@aristocratos  Thanks but now isn't it a little confusing to read? 
![image](https://user-images.githubusercontent.com/61059757/80280406-71799a80-8736-11ea-8fb8-c12b83490ec8.png)

**Comment by aristocratos** [comment]
fixed in v0.8.8

**Comment by aristocratos** [comment]
Btw are you using a 24-bit color capable terminal? The colors looks off.

**Comment by pappabewar** [comment]
I'm using MobaXterm on Windows, I believe it has it's own strange default colour settings

**Comment by aristocratos** [comment]
Ah ok, I guess it's emulating 24-bit color with 256 colors since the gradients looks cut off.
