### ISSUE TITLE
Missing cpu range character

### ISSUE THREAD

**Issue by vycb** [aristocratos/bashtop#3]
There is problem to display cpu range character
![Bashtop cpu range](https://i.imgur.com/b4WwhWq.jpg)

**Comment by aristocratos** [comment]
Huh, gonna try and find a better suitable unicode character for that symbol. No other symbols showing up weird?

**Comment by vycb** [comment]
All other displays great, and look perfect

**Comment by aristocratos** [comment]
fixed in commit  [aaeb1b33d065384e58561acfcf36ac8341d735ff](https://github.com/aristocratos/bashtop/commit/aaeb1b33d065384e58561acfcf36ac8341d735ff)
