### ISSUE TITLE
[BUG] Misuse of . in regex comparison

### ISSUE THREAD

**Issue by Anvil** [aristocratos/bashtop#31]
Hi. I was still reading and found this one:

https://github.com/aristocratos/bashtop/blob/c910e2d4237428be1e488b734ae87809f41d32f1/bashtop#L732

`[[ $foo =~ . ]]` is actually `[[ -n $foo ]]`. 
I think what you wanted to meant was more `[[ $foo =~ \. ]]` or `[[ $foo = *.* ]]` (this form should be faster to run, iirc). 

Since `%.*` is idempotent when there's no `.` in foo's value, another possiblity would be to drop that test and do that
```bash
if [[ -n $int ]]; then
    found=${found%.*}
    if [[ -n $math ]]; then
        math=...
        found=...
    fi
fi
```

**Comment by aristocratos** [comment]
You're absolutely right.
That check is however also to convert any float to int and not just a check for running arithmetic.
But are gonna change the check and add a `printf "%.0f"` to properly round the value to integer.

**Comment by aristocratos** [comment]
I went with:
`		if [[ -n $int && $found =~ [.|,] ]]; then
			found="${found/,/.}"
			printf -v found "%.0f" "${found}"
		fi`

**Comment by aristocratos** [comment]
Fixed in v0.8.11

**Comment by Anvil** [comment]
The pipe does not seem necessary here, unless you want to match an actual pipe char.

**Comment by aristocratos** [comment]
Damn, even if it had worked as OR there it would have been useless. Should have been XOR to actually do anything.
But yes, not needed.

**Comment by Anvil** [comment]
Well, technically, this pattern will also match "a.b", and "1,,,@!$!$,zoom", so a full `^[0-9]+[,.][0-9]+$` should be prefered to avoid an error at the printf.

**Comment by aristocratos** [comment]
Any non numericals should've been cleared earlier in the search with the "-i" flag forcing following regex:
https://github.com/aristocratos/bashtop/blob/38863bd607cc10dd25d78bf044727c9cb7cd4d56/bashtop#L695
It's however possible it picks up for example "1." which I should probably check...
