### ISSUE TITLE
[BUG] no content displayed after execute bashtop

### ISSUE THREAD

**Issue by zffocussss** [aristocratos/bashtop#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**
![1587874024199](https://user-images.githubusercontent.com/46145695/80297575-e987a500-87b6-11ea-9312-83a9646ae486.jpg)

**Screenshots**

**Info (please complete the following information):**
 - Linux distribution and version
Description:	Ubuntu 16.04.4 LTS
 - System locale (output of "echo $LANG")
 - Bash version
en_US.UTF-8
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
**Additional context**
$HOME/.config/bashtop/error.log" (enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing)

![error](https://user-images.githubusercontent.com/46145695/80297566-c826b900-87b6-11ea-8590-f23ebd6c5ff7.jpg)

**Comment by aristocratos** [comment]
See #34
