### ISSUE TITLE
[BUG] Error: shopt: globasciiranges: invalid shell option name

### ISSUE THREAD

**Issue by wangzhe258369** [aristocratos/bashtop#34]
Error message：
```
./bashtop: line 33: shopt: globasciiranges: invalid shell option name
```

Environment：
* CentOS 7.0
* bash 4.1.2
* bashtop v0.8.10

**Comment by aristocratos** [comment]
Not a bug:

> bash (v4.4 or later) Script functionality will most probably break with earlier versions.

You need to either update bash manually or update CentOS.

**Comment by juzj** [comment]
Error message：

`./bashtop: line 33: shopt: globasciiranges: invalid shell option name`


Environment:

- CentOS Linux release 7.3.1611 (Core) 

- bash-4.2.46-33.el7.x86_64

- The latest version。

**Comment by juzj** [comment]
> 错误信息：
> 
> ```
> ./bashtop: line 33: shopt: globasciiranges: invalid shell option name
> ```
> 
> 环境：
> 
> * CentOS 7.0
> * bash 4.1.2
> * bashtop v0.8.10

Hello, has this problem been solved? I have the same problem on my side!

**Comment by aristocratos** [comment]
> 
> 
> Not a bug:
> 
> > bash (v4.4 or later) Script functionality will most probably break with earlier versions.
> 
> You need to either update bash manually or update CentOS.
