### ISSUE TITLE
Font coverage

### ISSUE THREAD

**Issue by shahzebs** [aristocratos/bashtop#38]
Is there a guideline for what kind of fonts I would need to be able to see the usage bars and graphs?

**Comment by aristocratos** [comment]
The symbols for the graphs are the braille unicode block U+2800 - U+28FF
The symbol for the meters is the unicode character 'BLACK SQUARE' U+25A0
So any font that covers those blocks will work, I doubt there are many monospaced fonts meant for use with terminals that don't cover them.

**Comment by HG1112** [comment]
I want to help with this issue . How can I start ?

**Comment by Project-Magenta** [comment]
@HG1112 there is no issue here. just move on to a different issue
