### ISSUE TITLE
[BUG] Text scrolling off the screen.

### ISSUE THREAD

**Issue by halon314** [aristocratos/bashtop#40]
**Describe the bug**
As the screen refreshes, a few lines (CPU Core 2 utilization and total Bytes uploaded) move to the right with each refresh.

**To Reproduce**
Steps to reproduce the behavior: Difficult to say.  It's always done this on my setup. The Linux machine I'm monitoring is a VM.  The host machine from which I access that machine is using the SSH plugin on Google Chrome.

**Expected behavior**
The two lines mentioned above should stay aligned with the rest of the information on the screen upon refresh.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/64379485/80318937-92e09200-87db-11ea-95c0-f11d77741f44.PNG)

**Info (please complete the following information):**
 - EndeavourOS Linux x86_64 Kernel: 5.6.5-arch3-1 
 - GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)

**Comment by aristocratos** [comment]
Have you tried another ssh client?
It looks like chromes ssh plugin are having problems rendering certain symbols at correct sizes.
Not really much I can do about it. I would suggest you submit a bug report with the team working on that ssh client.

**Comment by halon314** [comment]
Ah, yes.  I see it works fine from the console AND from another Linux box via SSH.
You may close this bug as a non-issue.  Thanks for the quick response and keep up the great work!  I love the app!

**Comment by aristocratos** [comment]
No problem, and thanks :)
