### ISSUE TITLE
[BUG] Freezing

### ISSUE THREAD

**Issue by SteMak** [aristocratos/bashtop#42]
**Description**
Bashtop freezes after trying to reverse, when additional info of pocess opened

**To Reproduce**
1. Open Bashtop
2. Press ↓ (down arrow)
3. Press ↵ (enter)
4. Press "r".
5. It freezed!

**Some info about test environment:**
Manjaro Linux 20.0
Bash version 5.0.16
Linux kernel 5.6.7-1-MANJARO

**Comment by aristocratos** [comment]
Yeah, that's not supposed to happen, but replicated and confirmed.
It does however unfreeze when any other key is pressed.
Gonna take a look at it before next update.

**Comment by aristocratos** [comment]
Fixed in v0.8.15
