### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by njnj-gif** [aristocratos/bashtop#47]
Current size:                                 │
80x24 
 Need to be atleast: 
80x25

**Comment by aristocratos** [comment]
Please follow the bug report template when bug reporting:
https://github.com/aristocratos/bashtop/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

From the output posted I would say resize your terminal?
If you are NOT running bashtop in a terminal emulator, there is gonna be problems even if I reduce the limit to 80x24, like cut off text, some symbols are most likely not gonna work and possibly problems with screen update speed.
