### ISSUE TITLE
Background colors with urxvt

### ISSUE THREAD

**Issue by GideonWolfe** [aristocratos/bashtop#5]
Arch Linux and urxvt
![bashtop](https://user-images.githubusercontent.com/32942052/78635472-2b2dcb80-785b-11ea-946c-757bc2c2de56.png)

**Comment by aristocratos** [comment]
You need a truecolor capable terminal to show truecolor colors.
You can try [rxvt-unicode-truecolor](https://aur.archlinux.org/packages/rxvt-unicode-truecolor) if you wanna keep using rxvt.

**Comment by ijiki16** [comment]
I think I have same problem but on MacOS Catalina.

![Screen Shot 2021-02-24 at 18 41 33](https://user-images.githubusercontent.com/37273763/109017224-697ce500-76d0-11eb-866e-d3d3122923bb.png)

Same in bash and zsh.

Program: Terminal 2.10 (433)

Any advices to fix colors?
