### ISSUE TITLE
[BUG] Array item should be quoted to avoid globbing to interfer

### ISSUE THREAD

**Issue by Anvil** [aristocratos/bashtop#50]
https://github.com/aristocratos/bashtop/blob/38863bd607cc10dd25d78bf044727c9cb7cd4d56/bashtop#L197

If you leave it unquoted, then a file named cpuh or cpuz can trigger globbing and change the command line. Also if failglob is enabled by the user, a globbing error might abort the script.

On the other hand, quotes on param_var are not necessary.

**Comment by aristocratos** [comment]
Shouldn't line 32 fix failglobbing?
https://github.com/aristocratos/bashtop/blob/38863bd607cc10dd25d78bf044727c9cb7cd4d56/bashtop#L32

The unquoted associative array might be a problem yes, it's likely to be more unquoted associative arrays.
Gonna take a look at it before next update.

**Comment by aristocratos** [comment]
Fixed the most obvious missed single quotes in v0.8.15

**Comment by Anvil** [comment]
Ha, you're right, I had not seen those shopts. So it wont trigger failglob :)
