### ISSUE TITLE
Enhancement Request - NVIDIA GPU monitoring

### ISSUE THREAD

**Issue by laytonjbgmail** [aristocratos/bashtop#51]
First - this is one awesome tool! Thanks a million!

Second - I use NVIDIA GPUs, and I would love if monitoring them could be incorporated into bastop. The needed metrics are exposed in the either /proc or /sys.

Thank you!

Jeff Layton

**Comment by aristocratos** [comment]
It's on the TODO list. It's probably gonna be a while though, since it's likely a lot of work to get consistency between brands and drivers.
