### ISSUE TITLE
Support for Centos

### ISSUE THREAD

**Issue by balmha** [aristocratos/bashtop#54]
Hi, how are you?. Im running Centos 7.8 for first time, im using bashtop in Debian and work perfectly, but in Centos Im have the next problem when im running ./bashtop:

./bashtop: line 33: shopt: globasciiranges: invalid shell option name

Im install all dependencies but not work, could you help me please?. Regards!

**Comment by gabsoftware** [comment]
Same issue here, with CentOS 7.8.2003. All dependencies installed.

**Comment by kiichi7** [comment]
The bash version in RHEL/CentOS 7 is 4.2, so you need to make a 4.4 version of Bash from the source code. It will work.

**Comment by aristocratos** [comment]
If you used the bug report template the issue would become pretty clear, as @kiichi7 pointed out.

> **Info (please complete the following information):**
> - Linux distribution and version
> - Bash version (version 4.4 or above is required)

I don't mean to sound rude, but this is like the 5th issue about CentOS 7. And everybody seems to fail to check bash version.

**Comment by gabsoftware** [comment]
I agree I should have checked the Bash version before commenting. But those issues could be avoided if the homepage clearly stated that the minimum Centos supported release is Centos 8 (like you did for RHEL 8).

**Comment by aristocratos** [comment]
The installation instructions for RHEL 8 and CentOS was added after this issue was opened and if installed with package manager would fail since it depends on bash 4.4>.

I however expect that if someone installs a program by cloning from github they would have read the dependencies listed, if not before installation at least before creating a bug report.

Listing all linux distributions which have bash 4.4 seems a like a long and unnecessary list in the readme.

**Comment by gabsoftware** [comment]
Just as an information for future readers, one can compile a newer Bash version very easily on CentOS 7:

`yum install wget
yum group install "Development Tools"
wget http://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz
tar -zxvf bash-5.0.tar.gz
cd bash-5.0
./configure
make
make install`

(add sudo where relevant if necessary)

This will install Bash 5.0 in /usr/local/bin and it will become your new bash.
Then, bashtop will run.

**Comment by balmha** [comment]
Hi guys, update to bash4.4 work for me, regards!!
