### ISSUE TITLE
[REQUEST] bashtop should fail gracefully if the Bash version is lower than 4.4

### ISSUE THREAD

**Issue by Calinou** [aristocratos/bashtop#55]
**Is your feature request related to a problem? Please describe.**

Yes. I tried bashtop on an Ubuntu 16.04 machine, which only has Bash 4.3. bashtop crashed a few seconds after starting, without displaying any error message. (It works fine on my other Fedora 31 machine, which has Bash 5.x.)

**Describe the solution you'd like**

bashtop should check the bash version and exit with a non-zero error code if the Bash version on the system is lower than 4.4.

I could look at implementing this if this feature is desired.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by aristocratos** [comment]
This would be a good idea and a easy fix. I can take a look at it tonight. But feel free to make a pull request if you feel like it.
