### ISSUE TITLE
Please add tree view of processes

### ISSUE THREAD

**Issue by Ygarr** [aristocratos/bashtop#57]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when No tree view like with "V" option in top ot "T" in htop

**Describe the solution you'd like**
Want to view processes like in with pstree utility

**Describe alternatives you've considered**
options in top, pstree, htop, ps -f --forest, glances(old) option.
**Additional context**

**Comment by aristocratos** [comment]
Good idea! Gonna take a look at it. Gotta make sure the "-f" flag for ps don't mess up the parsing of the output. And if so, fix it.

**Comment by aristocratos** [comment]
@Ygarr added in v0.8.22
