### ISSUE TITLE
[BUG] High CPU usage

### ISSUE THREAD

**Issue by bLuka** [aristocratos/bashtop#60]
**Describe the bug**
On my machine, `bashtop` often goes up to 50% of CPU usage on refreshes.

To be exact, it varies between 20% and 60% of CPU usage according to `htop`. Computed by itself, it doesn't go upper than 4% of CPU (different CPU usage calculation?).

I increased refresh delay up to 5s to reduce CPU usage, so that happens less.

**To Reproduce**

1. Launch bashtop

2. Observe CPU usage on refreshes

3. Decrease refresh delay (2s shows high CPU usage nearly constantly)

**Expected behavior**
Lower CPU usage.

I still find 15%-20% would be still high, but more acceptable.

Cf. tests on another machine below.

**Screenshots**
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
31145 root       20   0  217M  6896  2416 S 40.4  0.0  0:28.97 bash /usr/local/bin/bashtop
```

**Info (please complete the following information):**
 - Gentoo Linux 5.0.5
 - Bash v5.0.17
 - 4c/8t@3.6GHz CPU
 - ZFS root with 39 volumes mounted (is disk monitoring CPU intensive?)

**Additional context**
#### Error logs:
Here are my latest error logs (please note that I upgraded `bashtop` before further testing and opening this issue):
```
New instance of bashtop version: 0.8.5 Pid: 1651
09:44:08 ERROR: On line 1731 
09:44:11 ERROR: On line 1731 (MUTED!)
 
New instance of bashtop version: 0.8.15 Pid: 30665
 
New instance of bashtop version: 0.8.15 Pid: 31145
```

#### Version comparison:
Compared to `0.8.5`, CPU usage is lower on latest version (didn't reach 50% as far as I've seen), it's more between 20% to 40%

#### Tests on another machine:
On a remote 6c/12t@3.5GHz remote machine (bash v4.4.23, Gentoo Linux 5.3.7, no ZFS and 2 volumes), CPU usage on `htop` varies between 4% and 25% as I've seen.

This latest CPU usage sounds reasonable for me, if there's tweaks I can do on my main host I'd like to target this CPU usage. Is my 40%-50% CPU usage locally kind of common for `bashtop` or is it abnormal?

**Side note**
Thanks for your amazing work! (#59)

**Comment by aristocratos** [comment]
> To be exact, it varies between 20% and 60% of CPU usage according to htop. Computed by itself, it doesn't go upper than 4% of CPU (different CPU usage calculation?).

Htop by default shows cpu usage for the core/thread the process is running on, bashtop shows usage for the cpu as a whole. The calculation is done with data from /proc and and measured in milliseconds since last update, so should be fairly accurate.

> ZFS root with 39 volumes mounted (is disk monitoring CPU intensive?)

That's probably one reason for high cpu usage, but also a easy fix. Right now it iterates over all disks regardless of how much is printed in the end. Gonna change so it don't collect more than needed.

There are probably tons of more optimizations to be made, but haven't had time to focus on it yet. 

The other branch I'm working on with python psutil replacing most external tools have a high likelihood of reducing the cpu usage alot, since the process collection and some calculations will be done in inline python scripts. But it's gonna be a couple weeks probably to get it all working right since I'm also fixing bugs and adding features to the master branch.

Thanks for the sponsorship btw :)

**Comment by aristocratos** [comment]
Added a fix for a lot of mounts in v0.8.17.
Let me know if it didn't do any difference.

**Comment by vimalaguti** [comment]
I find that on my raspberry pi 3B+ the cpu usage is fairly high - like 20-25%, but the measurement is not accurate.
Eg: bashtop is my only task, and in the task list it uses 8%, but in the cpu graph the usage is 20-25%.
While keeping it open, in another terminal, I opened htop and it shows bashtop uses 1 core, often at 79-80% (which actually is 20-25% of the total).

refresh is 2500ms, temp true, theme monokai-nobg, there are only 3 mounted partitions (boot, root, external)

**Comment by RastogiAbhijeet** [comment]
Facing similar issues. I feel the refresh time is the victim over here. As I have observed that is affecting the cpu usage. 
**For anyone facing similar issues** - Reduce the refresh rate.
But still the CPU utilisation is quiet high as compared to _htop_

**Comment by aristocratos** [comment]
@vimalaguti You can swich to "per-core" process cpu usage in the options. The same as `top` shows by default.

The cpu usage can be optimized a bit. But it's still bash. I will start work on a complete python port with pypy3 compatibility this summer. If people are still interested by then :)

**Comment by bLuka** [comment]
I can confirm CPU usage is better after the fix for several volumes mounted :tada: 

It's still high, but I guess that's out of the scope of the original issue and it should be closed, or would @aristocratos like to keep feeding this one untill Python version?

**Comment by aristocratos** [comment]
> I can confirm CPU usage is better after the fix for several volumes mounted

Awesome :)

We can keep this open to give attention to it and hopefully people can come with some suggestions for further optimizations.

**Comment by drazil100** [comment]
> But it's still bash. I will start work on a complete python port with pypy3 compatibility this summer. If people are still interested by then :)

I would very much be interested in a python version of this. You easily have the best looking terminal based system monitor on the market and it honestly performs way better than I would expect for being written in bash. Id love to see what you could do with this in python.

**Comment by bLuka** [comment]
Will it be called “pytop”?

**Comment by aristocratos** [comment]
Already exists a couple of "pytop" projects. But I was thinking maybe "PyPyTop" to bring attention to pypy3 being preferred interpreter.. and because it kinda sounds like ZZ Top :)
