### ISSUE TITLE
[BUG] Color theme numbering is wrong without additional themes

### ISSUE THREAD

**Issue by deluxe** [aristocratos/bashtop#61]
When using bashtop without additional color themes, the Default theme is used but its numbering in the Options menu is wrong: "**Color theme: 2/1**".

**Steps to reproduce the behavior:**
Delete or empty the `~/.config/bashtop/themes` directory. Launch bashtop and display the Options menu (either by `Esc` + Options menu selection or by `o` shortcut).

**Expected behavior:**
When displaying the Options menu, the numbering should read: "**Color theme: 1/1**".

**Info:**
 - Linux distribution and version: Ubuntu 19.10
 - Bash version: 5.0.3(1)-release

**Comment by deluxe** [comment]
Pull request to fix this issue: #62.

**Comment by aristocratos** [comment]
Good find!
