### ISSUE TITLE
[REQUEST] Reset Network Download/Upload Totals

### ISSUE THREAD

**Issue by djhmateer** [aristocratos/bashtop#63]
It would be nice to be able to reset the network Download/Upload Totals
![1](https://user-images.githubusercontent.com/111231/80475752-43b47180-8941-11ea-9b25-d2824de1b33c.jpg)

A keyboard shortcut would be ideal

I've found that reboot the machine resets the totals currently.

**Comment by aristocratos** [comment]
The current values are collected from /proc/net/dev.
But shouldn't be a problem to add a key for resetting the variable by negating current value.
Gotta take look at if the value in /proc/net/dev is reset at other times than at reboot though.

**Comment by djhmateer** [comment]
Much appreciated @aristocratos

**Comment by Calinou** [comment]
Speaking of which, is there an use for displaying the values in both bytes and bits? It feels a bit redundant to me. I think it'd be better to display just the values in bytes.

**Comment by aristocratos** [comment]
Added in v0.8.18

**Comment by djhmateer** [comment]
Wow great job - working well thank you @aristocratos
