### ISSUE TITLE
[REQUEST] Fedora package

### ISSUE THREAD

**Issue by alcir** [aristocratos/bashtop#67]
FYI I submitted a review request to Fedora in order to have bashtop installable from the Fedora repository.

**Comment by aristocratos** [comment]
Awesome :)

**Comment by AquaL1te** [comment]
Excellent! You beat me to it :) Otherwise I would've done it. [But looks good to me!](https://src.fedoraproject.org/rpms/bashtop/blob/master/f/bashtop.spec)
