### ISSUE TITLE
"Check Temp" option : unable to set "true" and show CPU cores temp

### ISSUE THREAD

**Issue by dasnoopy** [aristocratos/bashtop#69]
**Describe the bug**

Unable to set "Check temp"  to true ..it remains 9 times out 10 always on false

**To Reproduce**
- Open Options; goto "Check temp" options 
- press left or right key or ENTER key 
- value doesn't change to "true" and cores cpu temp are not displayed (I see only empty spaces). 

sometimes value change from **false** to **true** ,  but  CPU cores temps are not yet displayed .. 

**Expected behavior**
Check temp should be "true"  and cores cpu temp displayed

![Screenshot-28042020_1943_1](https://user-images.githubusercontent.com/296922/80519932-08d62c00-8989-11ea-8a8c-2a1920eb109e.png)

![Screenshot-28042020_1943](https://user-images.githubusercontent.com/296922/80520982-8cdce380-898a-11ea-952d-eb39af4e756c.png)

**Info (please complete the following information):**
 - Archlinux 64 bit update
- bashtop vers. 0.8.16
- Tilix terminal emulator
```
19:40:23 [andrea@wilcox]: ~ $tilix -v
Versions
	Tilix version: 1.9.1
	VTE version: 0.60
	GTK Version: 3.24.20
```

```
19:41:12 [andrea@wilcox]: ~/Downloads/test/bashtop-master $bash --version
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
19:41:20 [andrea@wilcox]: ~/Downloads/test/bashtop-master $which sensors
/usr/bin/sensors
19:41:22 [andrea@wilcox]: ~/Downloads/test/bashtop-master $sensors | grep Core
Core 0:       +39.0°C  (high = +72.0°C, crit = +100.0°C)
Core 1:       +39.0°C  (high = +72.0°C, crit = +100.0°C)
Core 2:       +36.0°C  (high = +72.0°C, crit = +100.0°C)
Core 3:       +41.0°C  (high = +72.0°C, crit = +100.0°C)
19:41:27 [andrea@wilcox]: ~/Downloads/test/bashtop-master $
```

**Additional context**
$HOME/.config/bashtop/error.log" (enable error-logging in "$HOME/.config/bashtop/bashtop.cfg" if missing)
`
New instance of bashtop version: 0.8.16 Pid: 9934`

Regards 
Andrea

**Comment by aristocratos** [comment]
Would you mind posting the complete output when you run `sensors`

**Comment by dasnoopy** [comment]
...here it is:

```
19:33:44 [andrea@wilcox]: ~ $sensors
w83627dhg-isa-0290
Adapter: ISA adapter
Vcore:         2.04 V  (min =  +2.04 V, max =  +2.04 V)  ALARM
in1:           2.04 V  (min =  +2.04 V, max =  +2.04 V)  ALARM
AVCC:          4.08 V  (min =  +4.08 V, max =  +4.08 V)  ALARM
+3.3V:         4.08 V  (min =  +4.08 V, max =  +4.08 V)  ALARM
in4:           2.04 V  (min =  +2.04 V, max =  +2.04 V)  ALARM
in5:           2.04 V  (min =  +2.04 V, max =  +2.04 V)  ALARM
in6:           2.04 V  (min =  +2.04 V, max =  +2.04 V)  ALARM
3VSB:          4.08 V  (min =  +4.08 V, max =  +4.08 V)  ALARM
Vbat:          4.08 V  (min =  +4.08 V, max =  +4.08 V)  ALARM
cpu0_vid:    +0.000 V
intrusion0:  ALARM

nouveau-pci-0100
Adapter: PCI adapter
GPU core:          1000.00 mV (min =  +0.95 V, max =  +1.05 V)
GeForce 9800 fan : 2166 RPM
GeForce 9800 temp:  +49.0°C  (high = +95.0°C, hyst =  +3.0°C)
                             (crit = +95.0°C, hyst =  +5.0°C)
                             (emerg = +125.0°C, hyst = +10.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +34.0°C  (high = +72.0°C, crit = +100.0°C)
Core 1:       +34.0°C  (high = +72.0°C, crit = +100.0°C)
Core 2:       +31.0°C  (high = +72.0°C, crit = +100.0°C)
Core 3:       +37.0°C  (high = +72.0°C, crit = +100.0°C)

19:33:50 [andrea@wilcox]: ~ $


```

**Comment by aristocratos** [comment]
Ah, ok, suspected that. Package temperature is missing, and have it set to stop if it fails on getting "Package".
Should be an easy fix. Will look at it later.

**Comment by aristocratos** [comment]
Fixed in v0.8.17

**Comment by fcmircea** [comment]
If I may, this seems to occur again on ubuntu 20.04 and 0.9.25.

Output of sensors on my system:

`fcmircea@hal9001:~$ sensors
tg3-pci-0300
Adapter: PCI adapter
temp1:        +83.0°C  (high = +100.0°C, crit = +110.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:         +8.3°C  (crit = +31.3°C)

tg3-pci-0301
Adapter: PCI adapter
temp1:        +83.0°C  (high = +100.0°C, crit = +110.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +57.0°C  (high = +85.0°C, crit = +105.0°C)
Core 0:        +53.0°C  (high = +85.0°C, crit = +105.0°C)
Core 1:        +57.0°C  (high = +85.0°C, crit = +105.0°C)
Core 2:        +50.0°C  (high = +85.0°C, crit = +105.0°C)
Core 3:        +55.0°C  (high = +85.0°C, crit = +105.0°C)`

What should I tray? Cheers.

**Comment by carlosrberto** [comment]
I have the same issue running Ubuntu 20.04 on Raspberry PI 4 and bashtop 0.9.25.

My sensors output is:
```
cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +57.5°C

rpi_volt-isa-0000
Adapter: ISA adapter
in0:              N/A
```

**Comment by vmiimu** [comment]
same issue -- any suggestions?
installed from snap

```
$ cat /etc/os-release 
NAME="KDE neon"
VERSION="5.22"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.22"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ sensors
BAT0-acpi-0
Adapter: ACPI interface
in0:          16.24 V  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +60.0°C  (high = +84.0°C, crit = +100.0°C)
Core 0:        +57.0°C  (high = +84.0°C, crit = +100.0°C)
Core 1:        +55.0°C  (high = +84.0°C, crit = +100.0°C)
Core 2:        +58.0°C  (high = +84.0°C, crit = +100.0°C)
Core 3:        +55.0°C  (high = +84.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +60.0°C  (crit = +99.0°C)
temp2:        +60.0°C 
```

**Comment by dmitrygribenchuk** [comment]
Hello. Have the same on Ubuntu 22.04.2 (Lenovo AMD laptop).
Bashtop 0.9.25

grid@nb000566:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

grid@nb000566:~$ sensors
thinkpad-isa-0000
Adapter: ISA adapter
fan1:        4330 RPM
CPU:          +68.0°C  
GPU:              N/A  
temp3:        +68.0°C  
temp4:         +0.0°C  
temp5:        +68.0°C  
temp6:        +68.0°C  
temp7:        +68.0°C  
temp8:         +0.0°C  

amdgpu-pci-0400
Adapter: PCI adapter
vddgfx:        1.40 V  
vddnb:       734.00 mV 
edge:         +62.0°C  
PPT:          20.12 W  

BAT0-acpi-0
Adapter: ACPI interface
in0:          16.29 V  

ath11k_hwmon-pci-0200
Adapter: PCI adapter
temp1:        +68.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +68.5°C  

nvme-pci-0300
Adapter: PCI adapter
Composite:    +59.9°C  (low  =  -0.1°C, high = +85.8°C)
                       (crit = +86.8°C)
Sensor 1:     +57.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +53.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +20.0°C  (crit = +110.0°C)

**Comment by rabaimorp** [comment]
Same here on arch linux, on  v0.9.25 my "sensors" also works fine
