### ISSUE TITLE
2 Bugs - Stuck at 100% CPU usage and Avail and the used bar is too close to the percent

### ISSUE THREAD

**Issue by RobertKarash** [aristocratos/bashtop#71]
The Memory Used - Avail Bar is too close to the percentage and the used bar under disks:
![screen1](https://user-images.githubusercontent.com/64501731/80542033-4b443c80-897a-11ea-9adc-4e86d5300066.jpg)
CPU Says 100%:
![screen1](https://user-images.githubusercontent.com/64501731/80539390-6f514f00-8975-11ea-947c-d1c6cb0f1265.jpg)
Next Terminal Tab:
![screen2](https://user-images.githubusercontent.com/64501731/80539361-606a9c80-8975-11ea-8ff5-6a1be73758fc.jpg)

In addition, I made this for Linux and included bashtop in my collection under tools:
https://t.co/IqL07177O6?amp=1

**Comment by RobertKarash** [comment]
I am using lubuntu Linux and qterminal

**Comment by RobertKarash** [comment]
This could also be from hardware failure. Can you refresh it somehow if the cpu hits 100%? I'm a developer; but I am currently working on other projects. I would love to see this implemented.

**Comment by aristocratos** [comment]
Use bug report template.
