### ISSUE TITLE
[BUG] bashtop symbols go down for some reason after a while 

### ISSUE THREAD

**Issue by bearybruh** [aristocratos/bashtop#76]
after some time with bashtop open. the cpu usage graph goes down to the mem and disks part 

how to reproduce: just have bashtop open for a while 

I expected that the graph would stay in the square for cpu 

ss: https://0x0.st/ietA.png

info:
current version in the arch repo
arch  with 86_64 Linux 5.6.7-arch1-1 kernel
tilda 
kiwi
version 5.0.16(1)-release

https://pastr.io/raw/4AraoLAH1k0 could be it im not sure

**Comment by bearybruh** [comment]
also there are some missing symbols at the cpu core graphs and on the sides of the squares. ss: https://0x0.st/ievB.png , https://0x0.st/ievM.png

**Comment by aristocratos** [comment]
Would you mind posting the output of `locale -v`

**Comment by bearybruh** [comment]
https://pastr.io/raw/5ByP4EqF5h9

**Comment by aristocratos** [comment]
It needs a UTF8 locale to show the correct symbols.
You can test it with `LC_ALL=en_US.UTF-8 bashtop` if you have en_US.UTF8 locale generated. Otherwise see https://wiki.archlinux.org/index.php/locale

**Comment by aristocratos** [comment]
Added more info to solve similar problems in [README.md#compatibility](https://github.com/aristocratos/bashtop#compatibility)

**Comment by bearybruh** [comment]
alright "LC_ALL=en_US.UTF-8 bashtop" works just fine. im gonna use it. thanks

**Comment by bearybruh** [comment]
nevermind. still got issues. here is an ss https://0x0.st/ievg.png

**Comment by bearybruh** [comment]
by the way your ascii kinda messed up https://0x0.st/ievE.png

**Comment by bearybruh** [comment]
and appreantly LC_ALL=en_US.UTF-8 bashtop didnt really fix it. https://0x0.st/iev6.png

**Comment by bearybruh** [comment]
or any of them https://0x0.st/ievI.png

**Comment by aristocratos** [comment]
You still need to set up your locales.
Backup `/etc/locale.conf`
and run `echo "LANG=en_US.UTF-8" > /etc/locale.conf`
Then reboot and see if you still have problems.
If so, try another font.

**Comment by aristocratos** [comment]
Or follow the guide at https://wiki.archlinux.org/index.php/Locale#Setting_the_locale

**Comment by bearybruh** [comment]
pretty sure it works well now. thanks

**Comment by aristocratos** [comment]
Np, would you mind taking another screenshot, would like to see how it looks when working with that font :)

**Comment by bearybruh** [comment]
https://0x0.st/ievR.png I love kiwi so much. pixely fonts are the best

**Comment by aristocratos** [comment]
Thats pretty :)
Remember where you got it? Can't find it searching google.

**Comment by bearybruh** [comment]
I cant find it. would you mind if I post it on google drive and send the link here? or if you want another file hosting service

**Comment by aristocratos** [comment]
Or you can mail it to admin@qvantnet.com if you don't mind :)

**Comment by bearybruh** [comment]
for sure. give me a sec

**Comment by bearybruh** [comment]
done

**Comment by aristocratos** [comment]
Thanks :)
Closing this issue.
