### ISSUE TITLE
[REQUEST] Choose which disks to display

### ISSUE THREAD

**Issue by dotslashcow** [aristocratos/bashtop#79]
**Is your feature request related to a problem? Please describe.**
I use multiple BTRFS subvolumes on a single disk, which are all detected as "disks". So I have 5 entries in the "disks" section that show the same usage, cluttering up the UI.

**Describe the solution you'd like**
I'd like to be able to choose which disks to display.

**Additional context**
![2020-04-30-13:22:57](https://user-images.githubusercontent.com/130760/80686060-c24a1400-8ae5-11ea-9320-01bae55b07b8.png)
For example in the screenshot, I would like to be able to only display "root", "windows" and "boot" as all the others are subvolumes on the same disk as "root" and show no useful info.

**Comment by aristocratos** [comment]
Yup, could add a option in the config to define which disks to display.
Like `disks_filter="root home music"`

**Comment by dotslashcow** [comment]
> Yup, could add a option in the config to define which disks to display.
> Like `disks_filter="root home music"`

Yes, that would be great!

**Comment by aristocratos** [comment]
Added in v0.8.18
