### ISSUE TITLE
Problem with mem a disks's chart

### ISSUE THREAD

**Issue by mtellezj** [aristocratos/bashtop#8]
Hi, the cpu and net charts render fine, but mem and disks are not. I'm tested with gnome-terminal and xfce4-terminal. Should I install a new font?

![image](https://user-images.githubusercontent.com/17144927/78958863-f914a780-7aae-11ea-8378-45bb8f0b5293.png)

**Comment by aristocratos** [comment]
Fixed in [b673325](https://github.com/aristocratos/bashtop/commit/b6733258f9fce0e4c63755cb2332e212259a0c81)

**Comment by mtellezj** [comment]
> Fixed in [b673325](https://github.com/aristocratos/bashtop/commit/b6733258f9fce0e4c63755cb2332e212259a0c81)

Thanks a lot. Good job by the way!
