### ISSUE TITLE
[BUG] Let user exit when window resize is required

### ISSUE THREAD

**Issue by Germano0** [aristocratos/bashtop#81]
I opened bashtop in Yakuake and I got the message `Current size: 170x24 Need to be atleast: 80x25` but since I cannot resize Yakuake, I just wanted to exit from bashtop, but I was unable.
Can you please add an option to exit, when the user is prompted to resize the window?

**Info (please complete the following information):**
 - Bashtop version: 0.8.17
 - Linux distribution and version: Fedora 31
 - Terminal used: Yakuake
 - Bash version: 5.0.11

**Comment by aristocratos** [comment]
My mistake, will add check for Ctrl+C.
Are you sure you were running version 0.8.17. Size requirements were lowered to 80x24 in that version.

**Comment by Germano0** [comment]
>  Are you sure you were running version 0.8.17. Size requirements were lowered to 80x24 in that version.

I originally filled the bugreport against 0.8.16, then I updated to 0.8.17 and saw that the requirements were lowered, so I reproduced using a very small Konsole session and I updated the version number in the bugreport without updating the error message with the new size

**Comment by aristocratos** [comment]
Ah, ok :)
Will fix issue in next update.

**Comment by aristocratos** [comment]
Fixed in v0.8.19
