### ISSUE TITLE
[BUG] bashtop corrupted over SSH

### ISSUE THREAD

**Issue by Generator** [aristocratos/bashtop#82]
**Describe the bug**
Symbols got corrupted when using bashtop over SSH connection

**To Reproduce**

`ssh user@host -t bashtop`

**Expected behavior**

[A clear and concise description of what you expected to happen.]

**Screenshots**

![bashtop-ssh](https://user-images.githubusercontent.com/44146/80759151-c0587300-8b2e-11ea-9db4-68a5adc73f64.png)
![bashtop-ssh-menu](https://user-images.githubusercontent.com/44146/80759159-c3ebfa00-8b2e-11ea-9104-f98bd039af59.png)

When using `bashtop` on a remote tmux session there's no issue
![ssh-tmux](https://user-images.githubusercontent.com/44146/80759453-3ceb5180-8b2f-11ea-8e3a-3e5ece0fa4e9.png)

**Info (please complete the following information):**
 - Bashtop version: 0.8.18
 - Linux distribution and version: Archlinux (local), DietPi/Raspbian (remote)
 - Terminal used: xfce4-terminal, termite
 - Font used: 'Inconsolata for Powerline'
 - Bash version: 5.0.16
 - Locales: output of "locale -v"

Local:
```
LANG=pt_PT.utf8
LC_CTYPE="pt_PT.utf8"
LC_NUMERIC=pt_PT.UTF-8
LC_TIME=pt_PT.UTF-8
LC_COLLATE="pt_PT.utf8"
LC_MONETARY=pt_PT.UTF-8
LC_MESSAGES="pt_PT.utf8"
LC_PAPER=pt_PT.UTF-8
LC_NAME=pt_PT.UTF-8
LC_ADDRESS=pt_PT.UTF-8
LC_TELEPHONE=pt_PT.UTF-8
LC_MEASUREMENT=pt_PT.UTF-8
LC_IDENTIFICATION=pt_PT.UTF-8
LC_ALL=
```

Remote: 
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Additional context**
error.log:
`New instance of bashtop version: 0.8.18 Pid: 9182`

bashtop.cfg:
```
#? Config file for bashtop v. 0.8.18

#* Color theme, looks for a .theme file in "$HOME/.config/bashtop/themes", "Default" for builtin default theme
color_theme="Default"

#* Update time in milliseconds, increases automatically if set below internal loops processing time, recommended 2000 ms or above for better sample times for graphs
update_ms="2500"

#* Processes sorting, "pid" "program" "arguments" "threads" "user" "memory" "cpu lazy" "cpu responsive"
#* "cpu lazy" updates sorting over time, "cpu responsive" updates sorting directly at a cpu usage cost
proc_sorting="cpu lazy"

#* Reverse sorting order, "true" or "false"
proc_reversed="false"

#* Check cpu temperature, only works if "sensors" command is available and have values for "Package" and "Core"
check_temp="false"

#* Draw a clock at top of screen, formatting according to strftime, empty string to disable
draw_clock="%X"

#* Update main ui when menus are showing, set this to false if the menus is flickering too much for comfort
background_update="true"

#* Custom cpu model name, empty string to disable
custom_cpu_name=""

#* Enable error logging to "$HOME/.config/bashtop/error.log", "true" or "false"
error_logging="true"

#* Show color gradient in process list, "true" or "false"
proc_gradient="true"

#* Optional filter for shown disks, should be names of mountpoints, "root" replaces "/", separate multiple values with space
disks_filter=""
```

PS: For reference here `bashtop` on xfce4-terminal [Archlinux]
![Captura de ecrã_2020-04-30_22-20-53](https://user-images.githubusercontent.com/44146/80760676-3067f880-8b31-11ea-9e08-26438021e384.png)

**Comment by aristocratos** [comment]
Does this happen in other terminals?
Does it happen on other remote machines?
Also can you test running locally on your Raspberry?

**Comment by Generator** [comment]
> Does this happen in other terminals?

[termite](https://github.com/thestinger/termite)
> Does it happen on other remote machines?

Tested with [Artix Linux](https://artixlinux.org/) (Mate) Live-CD on Virtualbox
![VirtualBox_ArchLinux_30_04_2020_23_54_55](https://user-images.githubusercontent.com/44146/80767074-f56cc180-8b3e-11ea-83f7-68d436209885.png)

**Comment by aristocratos** [comment]
How about with a couple different fonts?
If you wouldn't have included the locale information I would almost have been certain it was a locale error. Since it looks like that when not using a UTF8 locale.

**Comment by aristocratos** [comment]
Could there be any ssh settings messing with locales?

**Comment by aristocratos** [comment]
Possibly related: https://askubuntu.com/questions/421878/terminal-ssh-doesnt-display-utf-correctly

**Comment by djhmateer** [comment]
I've noticed the screen behaving strangely using https://cmder.net/ from Windows10, but it is fine using `cmd.exe`

![2020-05-01 09_26_29-Cmder](https://user-images.githubusercontent.com/111231/80793046-ecefa780-8b8d-11ea-9cdc-22182e5bc34a.jpg)

**Comment by aristocratos** [comment]
Yeah, looks cmder don't render the braille symbols the graphs are created with in the right sizes.

**Comment by Generator** [comment]
Found the issue, looks like [dropbear](https://matt.ucc.asn.au/dropbear/dropbear.html) doesn't show characters correctly, after testing with OpenSSH there's no issues with `bashtop`.


| **OpenSSH**  | **Dropbear**  |
|-------------------------|:-------------------------|
|![bashtop-openssh](https://user-images.githubusercontent.com/44146/80842151-c9157b80-8bf8-11ea-92be-e94212261388.png) | ![bashtop-dropbear](https://user-images.githubusercontent.com/44146/80842177-d7639780-8bf8-11ea-87bc-ded436b5a1ed.png) |
|![bashtop-openssh-menu](https://user-images.githubusercontent.com/44146/80842310-2ad5e580-8bf9-11ea-8bc2-59552919cce6.png) | ![bashtop-dropbear-menu](https://user-images.githubusercontent.com/44146/80842319-31fcf380-8bf9-11ea-9301-2f80e9545181.png)

Didn't find any solutions for `dropbear`, for future reference that should be added to 'Compatibility' on README

**Comment by aristocratos** [comment]
The problem seems to have been around for over 10 years!
https://bugs.launchpad.net/ubuntu/+source/dropbear/+bug/232064
There is a suggestion for a workaround in that thread:

> This bug applies also to Intrepid. A little workaround is to do:

echo "export LANG=\"cs_CZ.UTF-8\"" > /etc/profile.d/lang.sh

as root.

Tried it?

**Comment by Generator** [comment]
Added `LANG=en_US.UTF-8` to `/etc/profile.d/lang.sh`, restarted `dropbear`, had no effect

**Comment by aristocratos** [comment]
Any difference if you run it with
```
LC_ALL=en_US.UTF-8 bashtop
```

**Comment by aristocratos** [comment]
I guess there's not a lot to do about it unless the dropbear developers fixes it then.

**Comment by Generator** [comment]
Tried 
`ssh user@host -t env LC_ALL=en_US.UTF-8 bashtop`
and 
` LC_ALL=en_US.UTF-8 ssh user@host -t  bashtop`

None had any affect

> I guess there's not a lot to do about it unless the dropbear developers fixes it then.

Maybe in the future, dropbear has a slow development, don't think it will be so soon.

**Comment by aristocratos** [comment]
Closing this issue now, since the bug is with dropbear and not bashtop.
