### ISSUE TITLE
Buggy in yakuake bash.

### ISSUE THREAD

**Issue by nardev** [aristocratos/bashtop#83]
Sadly but the processor chart is bit buggy. What ever size of window is...

![Screenshot from 2020-05-01 13-12-14](https://user-images.githubusercontent.com/696054/80801796-c2ade200-8bad-11ea-815b-87625c57857d.png)

**Comment by aristocratos** [comment]
From https://unix.stackexchange.com/questions/112018/make-yakuake-outputting-correct-characters

> ah, by setting export TERM='xterm -u8' it works ^^ thanks – Kokizzu Feb 2 '14 at 3:18

See if that does anything.

**Comment by nardev** [comment]
Unfortunately it didn't help. It starts ok but by the time it just expends in the right so it goes under/over the text with Cores.

**Comment by nardev** [comment]
Though, it's definitely a yakuake issue. The other terminal's work ok.

![Screenshot from 2020-05-01 13-26-47](https://user-images.githubusercontent.com/696054/80802418-87acae00-8baf-11ea-867f-fb3169cccc24.png)

**Comment by aristocratos** [comment]
Yeah, unfortunately I don't think there is much I can do on my end. I would recommend finding a alternative to yakuake, like Tilda.

**Comment by aristocratos** [comment]
Some possible alternatives https://www.reddit.com/r/LinuxActionShow/comments/2w64s4/guake_or_guake_alternatives/

**Comment by nardev** [comment]
@aristocratos man you want me to change 15 years old habit? I even use it with gnome man :D hahaha

**Comment by aristocratos** [comment]
:)

Try reporting bug to https://kde.org/applications/system/org.kde.yakuake

Maybe something will happen.

**Comment by aristocratos** [comment]
For more info, it seems to be especially the "Unicode Block “Braille Patterns” U+2800 - U+28FF" thats problematic.

**Comment by fliker09** [comment]
Damn, what a shame! Konsole/yakuake get stuck at _Running mem collection init..._ :-(

**Comment by aristocratos** [comment]
@fliker09 I don't think that's the same issue since it runs fine in Konsole 19.04.3
Check your error.log and make a bug report if you can't figure out whats causing it.
