### ISSUE TITLE
[BUG] CPU% - bug or feature?

### ISSUE THREAD

**Issue by djhmateer** [aristocratos/bashtop#86]
On an 8 core machine, the CPU% on a maxed out single thread process is 12.5%, yet on top shows as 100%. 

Is this a bug or feature? I can see the merits of both :-)

![2020-05-02 07_21_55-dave@blctest34_ ~](https://user-images.githubusercontent.com/111231/80857530-d5c2bf80-8c4a-11ea-8bc9-abb49055eeb1.jpg)

![2020-05-02 07_22_37-dave@blctest34_ ~](https://user-images.githubusercontent.com/111231/80857531-db200a00-8c4a-11ea-83c1-8142ac585609.jpg)

**Comment by aristocratos** [comment]
No that's a feature of bashtop dividing cpu usage between threads. So it would only hit 100% if the process was using 100% of every core. You can switch top to show like this too:

> You can change this behavior by pressing I (that's Shift + i and toggles "Irix mode") while top is running. That will cause it to show the pecentage of available CPU power being used. As explained in man top

Thats also why top can show more than 100% for a process in default mode.

Could add a option to switch to per core usage if there is interest?

**Comment by aristocratos** [comment]
Added option to show per core process cpu usage in v0.8.22

**Comment by djhmateer** [comment]
Awesome thank you very much for the %cpu feature - it makes looking at my server perf much easier now. 

I haven't spotted the locale issues on the graphs. Debugged them for a while and couldn't get to the bottom of it. Not a big problem for me. I'll open an issue but feel free to ignore it :-)

**Comment by aristocratos** [comment]
@djhmateer 
No problem :)
You are running through cmd right?
In that case you should look at this related fix for correct symbols:
https://github.com/aksakalli/gtop/issues/21
