### ISSUE TITLE
Add support to MacOS.

### ISSUE THREAD

**Issue by LyhourChhen** [aristocratos/bashtop#87]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aristocratos** [comment]
Already in the works if you read the README.md.
But it's gonna be while since it's a lot of coding and testing to be done and not a lot of spare time.

**Comment by RakibFiha** [comment]
I cannot seem to find the branch for psutil

**Comment by aristocratos** [comment]
It's not pushed to remote yet. It's still in testing and not usable in any capacity yet.

**Comment by aristocratos** [comment]
@RakibFiha 
Mac OS X support added in v0.9.0
