### ISSUE TITLE
[REQUEST] Raspberry Pi temperature

### ISSUE THREAD

**Issue by Generator** [aristocratos/bashtop#88]
**Description**
Raspberry Pi doesn't work with `lm-sensors` (lm-sensors/lm-sensors#30), however it has is own command to show CPU temperature

**Describe the solution you'd like**
There's two different ways to get CPU temperature.

With vcgencmd
```
$ vcgencmd measure_temp
temp=52.1'C
```

From thermal_zone
```
$ cpu=$(</sys/class/thermal/thermal_zone0/temp)
$ echo "$((cpu/1000))"
52
```

**Additional context**
Documentation: 
https://www.raspberrypi.org/documentation/raspbian/applications/vcgencmd.md
https://elinux.org/RPI_vcgencmd_usage
https://www.cyberciti.biz/faq/linux-find-out-raspberry-pi-gpu-and-arm-cpu-temperature-command/

**Comment by aristocratos** [comment]
Is vcgencmd exclusive to raspberry pi and usually included in all dists?

**Comment by aristocratos** [comment]
I would hesitate to use "/sys/class/thermal/thermal_zone0/temp" since without confirming the system is running on a raspberry pi, non cpu temps could be assigned to the cpu measurement on non intel or amd cpus.

**Comment by Generator** [comment]
> Is vcgencmd exclusive to raspberry pi and usually included in all dists?

Yes, is part of [raspberrypi-firmware](https://github.com/raspberrypi/firmware)

**Comment by aristocratos** [comment]
@Generator Added in v0.8.23
