### ISSUE TITLE
Not showing stats in macOS 

### ISSUE THREAD

**Issue by ggMartinez** [aristocratos/bashtop#9]
Hi

I'm using macOS High Sierra with bash 5.0, and the app loads but shows no data.

![Screen Shot 2020-04-10 at 4 45 33 PM](https://user-images.githubusercontent.com/5861971/79018692-d0da8680-7b4a-11ea-91c3-312ac06a2853.png)

**Comment by aristocratos** [comment]
Well i would point out that reason for that is pretty clear in the readme: "Linux resource monitor"

Would have to rewrite some pretty big chunks to get the same functionality on OSX since right now most data is collected from "/proc" and a lot of different linux specific programs.
Might happen in the future, but not until it's feature complete and bug free on linux.

**Comment by captain-kark** [comment]
I would expect this to be [mentioned in the readme](https://github.com/aristocratos/bashtop#compability) (emphasis mine):

> Should work on most **modern linux distributions** with a truecolor capable terminal.

As BSD is a "Unix-like" operating system, it doesn't count here. I think this could easily be misconstrued by readers who aren't aware of this distinction.

For those who are reading this issue in the future, supporting this on MacOS will probably never happen. Aside from the lack of `/proc` information, I can attest that many "simple" things aren't possible without significant overhead using `brew`'s GNU-flavored versions of many common binaries. One example that I discovered recently is that you can't get milliseconds, microseconds, or nanoseconds from the system time without using `perl`. BSD's `date` only returns seconds.

**Comment by aristocratos** [comment]
> Currently rewriting to use python3 psutil for data collection instead of linux specific tools. This will add python 3 and psutil as dependencies, but will make bashtop cross platform compatible.

So should have it working on OSX in a couple of weeks, and time milliseconds is taken cared of with bash 5 $EPOCHREALTIME variable.
