### ISSUE TITLE
Graph morse symbols showing a ? from Windows terminal

### ISSUE THREAD

**Issue by djhmateer** [aristocratos/bashtop#91]
From a Windows 10 latest patched machine I'm getting this from local Ubuntu 18.04 WSL:

![2020-05-03 10_11_22-Window](https://user-images.githubusercontent.com/111231/80910370-e34d7780-8d26-11ea-8943-193b818c134b.jpg)

and connecting to a remote Ubuntu 18.04 server in Azure from cmd.exe terminal on Windows 10:

![2020-05-03 10_12_09-Window](https://user-images.githubusercontent.com/111231/80910357-cadd5d00-8d26-11ea-960e-0f8c27dea7b5.jpg)

I've tried changing the locale settings on the remote server https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue

sudo locale-gen en_GB.UTF-8 en_GB
sudo dpkg-reconfigure locales
reboot

**Comment by aristocratos** [comment]
I just posted in your other issue.
aksakalli/gtop#21
It's a font problem and should be easily resolved by changing to a font with braille unicode block support.

**Comment by djhmateer** [comment]
Awesome that was it - thank you!

![2020-05-03 10_32_58-Window](https://user-images.githubusercontent.com/111231/80910744-80a9ab00-8d29-11ea-8846-14a81c8fb017.jpg)

**Comment by aristocratos** [comment]
Now it's looks prettier :)
