### ISSUE TITLE
[BUG] incomplete graph_symbol array

### ISSUE THREAD

**Issue by F-Hauri** [aristocratos/bashtop#94]
**Describe the bug**

graph_symbol array defined at line 163 miss all cases where there is more than 1 pixel diff between two points

**Expected behavior**

Use the whole UTF8 chars from \U2800 to \U28FF !!

**Info (please complete the following information):**
 - Bashtop version: 0.8.18
 - Linux distribution and version: debian buster
 - Terminal used: xterm
 - Font used: doen't matter
 - Bash version, "bash --version" (version 4.4 or above is required): 5+

**Comment by aristocratos** [comment]
I don't see how using the whole braille block of 256 characters would improve a representation of percent increase on a graph. The biggest block has 8 dots. The blocks used is a representing 10% increases of graph showing 0-100%. Any block that doesn't line up properly next to a smaller or bigger is just gonna create a mess of characters and empty spaces in the middle of the graph.

**Comment by aristocratos** [comment]
And how is this a bug?

**Comment by F-Hauri** [comment]
If some peek as to be shown; characters like `⣇`, `⡇` or `⢸` could be required!

**Comment by aristocratos** [comment]
Peaks are shown with `⣿` equals 100%, any non full width character would create empty space if the adjacent value is also above 90%

**Comment by F-Hauri** [comment]
If only 1 value is 100% and both adjacent are under 10%, I could expect `⣇`.

**Comment by F-Hauri** [comment]
Nota:

    ⣤⡀⢠⡄ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠠⣤⠀ ⠀⠀⠀⠀ ⢤⡄⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⢠⡄⠀ ⠀⢤⡄⠀ ⠀⢤⡄⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⢤⡄⠀⠀ ⠀⠀⠀⠀ ⠀⣠⢤⡀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⠀⠀⠀ ⠀⣠⣄⠀ 
    ⣿⠻⣾⡇ ⣴⣒⣲⡄ ⣶⠀⢰⡆ ⣴⣒⣲⡄ ⢲⡴⢲⡄ ⠀⠀⠀⠀ ⣶⠀⣶⠀ ⢴⡒⠲⠄ ⣴⣒⣲⡄ ⣠⠖⣿⠀ ⠀⠀⠀⠀ ⢸⡗⢦⡀ ⢲⡴⢲⡄ ⢐⣒⣦⠀ ⠀⢲⡆⠀ ⠀⢸⡇⠀ ⠀⢸⡇⠀ ⣴⣒⣲⡄ ⠀⠀⠀⠀ ⢸⡗⢦⡀ ⣴⣒⣲⡄ ⠠⣿⠄⠁ ⣴⠒⢲⡄ ⢲⡴⢲⡄ ⣴⣒⣲⡄ ⠀⢻⡟⠀ 
    ⣿⠀⢸⡇ ⢿⣀⣠⠄ ⠻⣄⡼⠃ ⢿⣀⣠⠄ ⣸⣇⠀⠀ ⠀⠀⠀⠀ ⢿⣀⢿⡀ ⢤⣉⣳⠄ ⢿⣀⣠⠄ ⢿⣀⢿⡀ ⠀⠀⠀⠀ ⢸⣇⣸⠇ ⣸⣇⠀⠀ ⢿⣀⢿⡀ ⠀⣸⣇⠀ ⠀⣸⣇⠀ ⠀⣸⣇⠀ ⢿⣀⣠⠄ ⠀⠀⠀⠀ ⢸⣇⣸⠇ ⢿⣀⣠⠄ ⢀⣿⡀⠀ ⢿⣀⣸⠇ ⣸⣇⠀⠀ ⢿⣀⣠⠄ ⠀⢨⡅⠀

**Comment by aristocratos** [comment]
Ok.. so make a pull request with the changes, and the added comparisons for the graph creation to compare against previous and next value.

**Comment by F-Hauri** [comment]
This seem linked to your other project: `spdtest`: You must show all possible steps:
    ⡀ ⡄ ⡆ ⡇ ⡀ ⣀ ⣄ ⣆ ⣇ ⡄ ⣄ ⣤ ⣦ ⣧ ⡆ ⣆ ⣦ ⣶ ⣷ ⡇ ⣇ ⣧ ⣷ ⣿

**Comment by aristocratos** [comment]
"Must" I? Haven't read the rules for creating graphs with braille symbols.

**Comment by F-Hauri** [comment]
It's only a must if you plan to make something not only pretty, but correct too.

**Comment by F-Hauri** [comment]
Sorry previous list was wrong:

 ⠀  ⢀ ⢠ ⢰ ⢸ ⡀ ⣀ ⣠ ⣰ ⣸ ⡄ ⣄ ⣤ ⣴ ⣼ ⡆ ⣆ ⣦ ⣶ ⣾ ⡇ ⣇ ⣧ ⣷ ⣿
⠀   ⠈ ⠘ ⠸ ⢸ ⠁ ⠉ ⠙ ⠹ ⢹ ⠃ ⠋ ⠛ ⠻ ⢻ ⠇ ⠏ ⠟ ⠿ ⢿ ⡇ ⡏ ⡟ ⡿ ⣿

**Comment by aristocratos** [comment]
Ah yes, very proper.

**Comment by F-Hauri** [comment]
In fine: I don't this this will triple calculation! Not even double, but you will have to store 2 array instead of only one!

Have a look! I just wrote this as a sample:

   https://f-hauri.ch/vrac/graph_braille.sh

**Comment by F-Hauri** [comment]
Corrected a littre bug in my https://f-hauri.ch/vrac/graph_braille.sh: removed wrong line `#0`.

**Comment by aristocratos** [comment]
The graph isn't actually generated from scratch at every update, it's saved to an array and updated. Take a look at the create_graph() function:

https://github.com/aristocratos/bashtop/blob/master/bashtop#L973-L1159

**Comment by F-Hauri** [comment]
Yes, of course, I already read your script...

Then you have to store them into **two** arrays: *even* and *odd*...

In my script, I don't generate graph from scratch on every update!

I just switch between `graphline_even[]` and `graphline_odd[]`, adding one char at end of each lines in either `even` or `odd`.

Note: array length is `$height-1` resolution is `$height-1)x4`. each entry contain 1 line:

    graphline_even[1]="⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
    graphline_even[2]="⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
    graphline_even[3]="⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
    graphline_even[4]="⢀⣄⣀⣄⣀⣀⣀⣠⣄⣤⣤⣸⣿⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣤⣄⣀⣀⣀⣀⣀⣀⣀⣄⣀⣀⣀⣀⣀⣀"
     graphline_odd[1]=" ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
     graphline_odd[2]=" ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
     graphline_odd[3]=" ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
     graphline_odd[4]=" ⣠⣀⣠⣀⣀⣀⣀⣤⣠⣤⣄⣿⣧⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⣤⣀⣀⣀⣀⣀⣀⣀⣠⣀⣀⣀⣀⣀⣀"

On each update, I just add 1 char at either graphline_odd or graphline_even. Compute crt val (0-4) for each line, then choose character by using previous val, then store val to previous and switch odd/even for next loop.

On `even`, first non blank char is `⢀` and on `odd`, first non blanki is `⣠`.

**Comment by F-Hauri** [comment]
Sample:

     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡀⠀⠀⠀⠀⠀⢰⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
     ⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⣠⣿⣇⣀⣀⣀⣤⣀⣼⣿⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀
     00:16:20.004623     1.50%  (last sleep: 0.997667 sec)

stored:

     graphline_odd[1]='⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣄⣼⣿⣀⣀⣀⣠⣄⣠⣿⣧⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀'
     graphline_odd[2]='⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'
     graphline_odd[3]='⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣇⠀⠀⠀⠀⠀⠀⣾⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'
     graphline_odd[4]='⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⢸⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'
    graphline_even[1]='⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⣠⣿⣇⣀⣀⣀⣤⣀⣼⣿⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀'
    graphline_even[2]='⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'
    graphline_even[3]='⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡀⠀⠀⠀⠀⠀⢰⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'
    graphline_even[4]='⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'
Compute how many pixel (height in pixel) for current value

        41      readGrSizes() {
        47          pixels=$[(height-1)*4]
       ...
        59              crtpix=$[pixels-(idlcpu-lastidl)*pixels/(utcpu-lastut)]

choose between *even* or *odd* array

        41      readGrSizes() {
        48          graphline_even=() graphline_odd=()
        ...
        60              declare -n crtline=graphline_${lnnames[evenodd]}
        ...
        88      lnnames=(even odd)
        89      declare -a graphline_even graphline_odd

Store previous value (or `0`) as `lval`

        62                  lval[i]=${val[i]:-0}

Append next char (`lval` `_` `val`) to string

        70                  crtline[i]+=${graph_chars_up[${lval[i]}_${val[i]}]}

Drop 1st char is string > width

        71                  ((${#crtline[i]}>width))&&crtline[i]=${crtline[i]:1}

Switch `even` / `odd`

        76              ((evenodd=1-evenodd))

**Comment by aristocratos** [comment]
Since you opened this and the issue is code you don't consider to be done "correct". Why don't you make a pull request with your suggested changes? This is after all github and not stackoverflow.

Otherwise I think your point has been made and I don't see a reason to keep this open unless others have anything to chime in.

**Comment by F-Hauri** [comment]
I'm sorry, but

If I find

 - interresting to see how bash could make such a complex work
 - beautiful and awesome this monitor, anyway
 - fun to play with braille fonts (I've already played with halfblocks:  " ▝▘▀▗▐▚▜▖▞▌▛▄▟▙█")

 I won't

 -  try to understand all your code,
 - spent more time on a [bash] program wich require huge amount of resources

So feel free to close this thread and try to integrate my improvement or switch to python then rewrite the whole engine (integrating my idea of even/odd array).

**Comment by aristocratos** [comment]
I don't mind discussing the subject and possible implementations.

But I don't know if it's a language barrier thing or if I'm misinterpreting, but you come off a bit hostile.

If that's not you intention then I apologize for being short with you.

**Comment by F-Hauri** [comment]
I'm sorry, not really well in english, my language is french.

Did not want to hurt you, 

On the contrary i would to encourage you to switch to python as you already shown a good programming skill

**Comment by aristocratos** [comment]
Ok, and thanks :)

Yeah, gonna start porting to python this summer when I've got some more time. Hard to get in a good rhythm when coding in short bursts. Currently spending almost all of my free time to fixing bugs and building up scripts for the psutil version.

**Comment by aristocratos** [comment]
Added optional increased resolution graphs in v0.8.28
Does however eat a lot of cpu cycles.
