### ISSUE TITLE
Improvement: reduce forks

### ISSUE THREAD

**Issue by F-Hauri** [aristocratos/bashtop#95]
A lot of forks could be supressed:

    67  declare version="0.8.18"

.1: fork to date (if bash <v5)

     202                  read ms_out < <(date +%s%3N)

  by running *background process* trough a fifo:
   
    mkfifo /some/path/datefifo
    exec 5> >(exec stdbuf -o0 date -f - +%s%3N > /some/path/datefifo 2>&1)
    exec 6<  /some/path/datefifo
    rm  /some/path/datefifo
    get_ms() {
         echo now >&5 &&
             read -u 6 ms_out 
    }
  

.2 same for `tput`, see Optimizing bash: reducing forks by running tput as background process at https://unix.stackexchange.com/a/521120/27653 

Try my two scripts and compare execution times!

**Look my `nextFd` function!**

.3 useless fork to `tr`

    1697           proc[detailed_cmd]="$(tr '\000' ' ' </proc/${pid}/cmdline)"                             

by running `readarray` or `mapfile`:  
 
    mapfile -d $'\0' -n 0 cmdline <proc/${pid}/cmdline
    proc[detailed_cmd]=${cmdline[*]}
  

.4 useless fork to `printf` !!!

       470     echo "$(printf "%(%X)T") ERROR: On line $err $trap_muted" >> "${config_dir}/error.log"
  
Better written:

    printf "%(%X)T ERROR: On line  %s %s\n" -1 "$err" "$trap_muted" >> "${config_dir}/error.log"

**Comment by aristocratos** [comment]
1. Like the idea of running it in background but how is the compatibility with other platforms, OSX, BSD etc?

2. `tput` is only run in script init and script exit to set terminal options. So doesn't seem to be much point in running them in background. All color and cursor manipulation is done with escape codes.

3. Good find.

4. Rewrote it with a fork because I couldn't for the life of me get the time to output correctly. Turns out I was missing the `-1`.

**Comment by F-Hauri** [comment]
Anyway, I find this awesome, but bash is not a programming environment:

    xterm -fg grey -bg black -fs 10 -geom 160x48 -e 'bash /tmp/bashtop' & \
      sleep 4; read pid foo < <(ps -C bash w | grep bashtop) ;\
      while :;do
          printf "%(%a %d %b %T)T  " -1;
          ps who pid,etime,pcpu,pmem,vsz,rss,cmd $pid;
          sleep 600;
      done

will show:

    Sat 02 May 20:46:33  27196       00:04 25.5  0.0  11968  7460 bash /tmp/bashtop
    Sat 02 May 20:56:33  27196       10:04  9.3  0.0  12180  7672 bash /tmp/bashtop
    Sat 02 May 21:06:33  27196       20:04  9.3  0.0  12280  7740 bash /tmp/bashtop
    ...
    Sat 02 May 21:46:34  27196    01:00:04 10.1  0.0  12412  7904 bash /tmp/bashtop
    ...
    Sun 03 May 00:46:34  27196    04:00:05 10.6  0.0  13180  8668 bash /tmp/bashtop
    ...
    Sun 03 May 07:46:35  27196    11:00:06 11.3  0.0  14888 10376 bash /tmp/bashtop

So I can't make this run for a loong time...

Try python!! Same script will work better and more system friendly.

**Comment by aristocratos** [comment]
> So I can't make this run for a loong time...

So don't?

> Anyway, I find this awesome, but bash is not a programming environment:

Kinda is the point, didn't write this to create the most efficient resource monitor. But for fun and to try and get around the limits of bash and to expand my scripting abilities.

That there is other people interested in using it is a bonus, and if the interest grows it's possible I'll port it to python. Since I've already started replacing linux specific programs with python psutil for the osx and bsd version.

**Comment by F-Hauri** [comment]
> Would have to rewrite 90% of it...

Of course. but tool is nice and bash is overkill...

**Comment by F-Hauri** [comment]
... one more thing:

    var="${var}some more string"

could be more efficient if written:

    var+="some more string"

See: https://stackoverflow.com/a/47878161/1765658

**Comment by aristocratos** [comment]
Yeah, i know.

https://github.com/aristocratos/bashtop/blob/master/bashtop#L1625

https://github.com/aristocratos/bashtop/blob/master/bashtop#L3464

Works great for addition on declared integers too

https://github.com/aristocratos/bashtop/blob/master/bashtop#L434

**Comment by aristocratos** [comment]
Added in v0.8.25
[Possibilty to run date through background fifo for bash <5 ](https://github.com/aristocratos/bashtop/commit/576c391575303a7b37c1d8ae411f9e5ae6ce8c15)

**Comment by aristocratos** [comment]
Added in v0.8.26
[Fork cleanup and proc fixes](https://github.com/aristocratos/bashtop/commit/7f74cf40917d785d7a0b090f0367beff164479c1)
