### ISSUE TITLE
[REQUEST] disks box has redundant info

### ISSUE THREAD

**Issue by vimalaguti** [aristocratos/bashtop#98]
**Is your feature request related to a problem? Please describe.**
I think that the disks section has redundant information, and so is just more confusing. "Used" is just "total" - "free", or some devices/fs have more complex status?

**Describe the solution you'd like**
The solution is just to keep one of "used" or "free" row. And maybe free up some space for the iotop graph.

**Comment by aristocratos** [comment]
The "free" meter is only showed if there is enough room, the io stats doesn't have any graph creation. But that might get added as an option later.
